cmd/release-controller/sync.go
cmd/release-controller/types.go

Remove release tags:
* if Failed and not the newest
* if Rejected and not the newest 2 Rejected tags
* if Accepted and the "expires" config field is set to a duration, and not the latest accepted tag

Support an expiration for accepted tags and prune failures/rejects

---

cmd/release-controller/http.go

Gives flexibility for a release name to be different from tag name.

Handle pull spec being different from config name

---

cmd/release-controller/graph.go
cmd/release-controller/main.go
cmd/release-controller/sync.go

Allows edges to show up for testing

Add a cincinnati style graph to the release controller

---

cmd/release-controller/http.go

Should clarify where content goes.

Display more information on the index about publishing

---

cmd/release-controller/info.go

Use a PVC for caching git instead of an empty dir

---

cmd/release-controller/http.go
cmd/release-controller/http_helper.go
cmd/release-controller/sync.go
cmd/release-controller/types.go
cmd/release-controller/upgrades.go

Include links to at least see the diffs and results for triage.

Display from and to upgrades on the status page

---

cmd/release-controller/http_helper.go

Remove the reason from the phase display

---

cmd/release-controller/http.go

Failed to refactor the URL printf correctly.

Formatting string printed !(EXTRA) to page

---

cmd/release-controller/http.go
cmd/release-controller/http_helper.go

Also render style before markup so we don't get a flicker

Make the upgrade dot look clickable

---

cmd/release-controller/http.go

When no default was specified we were not setting PreviousRelease

Correctly set the change log inputs

---

cmd/release-controller/http.go
cmd/release-controller/http_helper.go
cmd/release-controller/release.go
cmd/release-controller/sync_check.go
cmd/release-controller/types.go

Catch places where people don't create the correct ART jobs or
the names don't match. Catch failures to build in a timely fashion.

Create a consistency check that looks for mismatches between streams

---

cmd/release-controller/http.go
cmd/release-controller/http_helper.go
cmd/release-controller/http_upgrade_graph.go

Add a section for setting this as a patch server.

Make the ugprade SVG more linear, link in overview

---

cmd/release-controller/sync.go

If tags to adopt aren't semantic we wedge. Instead, we should
continue in that scenario.

Don't wedge when some tags are not semantic

---

cmd/release-controller/info.go

Likely to reduce need to look at debug logs

Use changelog stderr to show output to user

---

cmd/release-controller/controller.go
cmd/release-controller/http.go
cmd/release-controller/http_helper.go
cmd/release-controller/info.go
cmd/release-controller/main.go

Create a files-cache stateful set that dynamically extracts tools and
serves them. A secret is optionally combined with the input if specified.

Show artifact downloads and describe `oc adm release extract --tools`

---

cmd/release-controller/info.go

Avoids having to refresh or getting partial output

Show an intersitial page while refreshing release contents

---

cmd/release-controller/info.go

Prepare to move away from shasum.txt.asc

---

cmd/release-controller/http.go
cmd/release-controller/http_helper.go
cmd/release-controller/sync.go
cmd/release-controller/types.go

Display info about them in the UI

Allow tags to be kept by setting annotation release.openshift.io/keep

---

pkg/prow/apiv1/load.go
pkg/prow/apiv1/types.go

Prow changed time durations to be strings instead of ints

---

cmd/release-controller/http.go
cmd/release-controller/http_helper.go
cmd/release-controller/http_upgrade_graph.go
cmd/release-controller/sync.go
cmd/release-controller/sync_tags.go
cmd/release-controller/types.go

Make debugging failures easier

Capture the last failure message and show on details page

---

cmd/release-controller/http.go

Naive scripting clients should be able to request parts of the response
* `format=name` - returns the name
* `format=pullSpec` - returns the pullSpec field
* `format=downloadURL` - returns the downloadURL
* `format=json` or `format=` - returns the full JSON object

Add additional ?format support for `api/v1/.../latest`

---

cmd/release-controller/http.go

Adding `rel=[0..N)` to a request for latest image will look backwards
that many places (i.e. 1 will locate the previous accepted tag).

Allow relative lookups of latest via `?rel=N`

---

cmd/release-controller/http.go

Apply rel independent of constraints

rel=N should work without a constraint

---

cmd/release-controller/sync.go
cmd/release-controller/sync_publish.go
cmd/release-controller/types.go

The OKD release will in the short term exclude several images

Allow image stream publish to exclude tags

---

README.md
cmd/release-controller/http.go

add build-cop bz query to overview dashboard

---

cmd/release-controller/http.go
cmd/release-controller/http_helper.go
cmd/release-controller/info.go

Try and find RHCoS change notifications and turn them into links
to the ART browser.
Make all links in the changelog open new tabs for convenience.

Add RHCoS diff link viewing to the changelog transformation

---

cmd/release-controller/http.go

Improves readability of the graph.

http: Omit external links on the stable release streams

---

cmd/release-controller/http.go
cmd/release-controller/http_helper.go

add links to specific releases to top of release overview pages

---

cmd/release-controller/bugzilla.go
cmd/release-controller/controller.go

controller: add more logging for bugzilla

---

cmd/release-controller/controller.go

controller: if should be checking `==` nil instead of `!=`

---

cmd/release-controller/controller.go

controller: use correct keys in bugzilla queue

---

cmd/release-controller/controller.go

Reverts openshift/release-controller#173

Revert "controller: use correct keys in bugzilla queue"

---

cmd/release-controller/bugzilla.go
cmd/release-controller/controller.go

bugzilla: fix bug

---

cmd/release-controller/bugzilla.go
cmd/release-controller/controller.go

Reverts openshift/release-controller#175

Revert "bugzilla: fix bug"

---

cmd/release-controller/bugzilla.go
cmd/release-controller/bugzilla_test.go
cmd/release-controller/controller.go
go.mod

Last PR still had a mistake that could cause panics. This PR reverts #177 and fixes the other bug.
/ cc @stevekuznetsov

Fix more bugs in bugzilla feature

---

cmd/release-controller/bugzilla.go

bugzilla: add more logging for errors

---

cmd/release-controller/info.go

Fix issue where there a no bugzilla bugs fixed between releases, which would result in strconv errors.

info: handle cases with empty "Bugs"

---

cmd/release-controller/bugzilla.go

bugzilla: log error from image client

---

pkg/bugzilla/bugzilla.go

Now that the bugzilla functionality appears to be functioning correctly, we can enable actual modification of bugzilla bugs.

bugzilla: make bugzilla pkg actually update bugs

---

cmd/release-controller/audit.go

Perform a simple purge of old jobs when we attempt to create a new
one. While this could race if the controller is in a slow crash
loop, it keeps the list pruned to recently relevant jobs effectively.

audit: Purge old verify jobs when we create new ones

---

cmd/release-controller/info.go

With the switch to UBI8 for base images, the python serving script
created within the cli image failed because of python2 to python3
changes. Adopt the changes from ci-tools and detect python2 and 3
to serve the appropriate version. Eventually python2 will be removed.

info: Support python3 in files cache serving

---

cmd/release-controller/periodic.go

The periodic config runner should have been setting the interval and
cron values for the periodics to what is set in the release periodic
config, but it was not.  This PR configures that correctly.

periodic: set interval and cron from release periodic config

---

cmd/release-controller/http_helper.go

It has been requested to distinguish blocking jobs from informing jobs on the
release stream page: [JIRA ticket](https://issues.redhat.com/browse/DPCR-26).
These changes slice the verification status, of the respective release, into
3 maps (blocking,informing, and pending) and then display the tests as a
nested list.
The existing logic produces the following output:
This PR updates output as follows:

Sorting tests by blocking,informing, and pending

---

cmd/release-controller/main.go

In investigating moving the release-controller's tools over to the app.ci cluster, it
has become apparent that we need to split up the single kubeconfig (--non-prow-job-kubeconfig)
into separate parameters that allow for creating the specific assets on the respective
cluster.  This PR adds 2 new parameters, --releases-kubeconfig and --tools-kubeconfig, to
allow us to split the imagestreams/jobs and the statefulsets, respectively, run on separate
clusters.  If not specified, these new parameters will default to the --non-prow-job-kubeconfig
value and then the in-cluster config.

Adding support to distribute the release-controller pieces onto different clusters

---

cmd/release-controller/info.go
test/testdata/jobs.yaml

replace hard-coded references to the wrong registry

---

cmd/release-controller/sync.go
cmd/release-controller/sync_mirror.go
cmd/release-controller/sync_release.go

sync: add more logging, reload IS for public repo

---

cmd/release-controller/sync.go

better log

---

cmd/release-controller/sync_release.go

jobs: use internal hostname for image

---

cmd/release-controller/main.go

This is the initial check-in to introduce the `--release-architecture` flag.  If not specified, it will be set to "amd64".  This commit will not change the existing behavior in any way.  It's simply to make the parameter available for all architectures to specify accordingly before we introduce logic that will depend on it being set appropriately.

Adding the --release-architecture flag

---

go.mod
go.sum
vendor/modules.txt

vendor: bump test-infra

---

go.mod
go.sum
vendor/k8s.io/test-infra/prow/config/config.go
vendor/k8s.io/test-infra/prow/kube/prowjob.go
vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
vendor/modules.txt

vendor: bump k8s.io/test-infra

---

cmd/release-controller/http_changelog.go

Fix RHCOS links for ARM

---

go.mod
go.sum
vendor/k8s.io/test-infra/prow/plugins/config.go
vendor/modules.txt

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

Update test-infra vendors

---

cmd/release-controller/main.go

There is something that is taking over 1 minute, during release-controller initialization, that's causing DPTP's Blackbox alarms to be triggered on a regular basis.  This PR simply adds some duration timers around the chunks of code that are executing between the container starting and the internal web server starting up to process requests.
I have repeatedly tried to reproduce this both locally and in our test environment with no success.  Ideally, this is just to try and pinpoint where the problem lies and then revert this commit.

Investigating initialization timings

---

go.mod
go.sum
vendor/k8s.io/test-infra/prow/config/branch_protection.go
vendor/k8s.io/test-infra/prow/config/config.go
vendor/k8s.io/test-infra/prow/config/inrepoconfig.go
vendor/k8s.io/test-infra/prow/config/prow-config-documented.yaml
vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
vendor/k8s.io/test-infra/prow/github/client.go
vendor/k8s.io/test-infra/prow/kube/BUILD.bazel
vendor/k8s.io/test-infra/prow/kube/config.go
vendor/k8s.io/test-infra/prow/plugins/plugins.go
vendor/modules.txt

Required by https://github.com/openshift/ci-tools/pull/2274
/cc @stevekuznetsov @alvaroaleman

Upgrade test-infra to d917e4a1e773

---

go.mod
go.sum
vendor/github.com/shurcooL/githubv4/README.md
vendor/github.com/shurcooL/githubv4/doc.go
vendor/github.com/shurcooL/githubv4/enum.go
vendor/github.com/shurcooL/githubv4/input.go
vendor/k8s.io/test-infra/prow/config/config.go
vendor/k8s.io/test-infra/prow/config/inrepoconfig.go
vendor/k8s.io/test-infra/prow/config/jobs.go
vendor/k8s.io/test-infra/prow/config/tide.go
vendor/k8s.io/test-infra/prow/crier/reporters/github/BUILD.bazel
vendor/k8s.io/test-infra/prow/crier/reporters/github/reporter.go
vendor/k8s.io/test-infra/prow/flagutil/github.go
vendor/k8s.io/test-infra/prow/flagutil/kubernetes_cluster_clients.go
vendor/k8s.io/test-infra/prow/git/git.go
vendor/k8s.io/test-infra/prow/git/v2/adapter.go
vendor/k8s.io/test-infra/prow/git/v2/interactor.go
vendor/k8s.io/test-infra/prow/github/client.go
vendor/k8s.io/test-infra/prow/github/report/report.go
vendor/k8s.io/test-infra/prow/github/types.go
vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
vendor/modules.txt

Required by https://github.com/openshift/ci-tools/pull/2306

Upgrade test-infra to e35aa846a43c

---

go.mod
go.sum
vendor/k8s.io/test-infra/prow/github/client.go
vendor/k8s.io/test-infra/prow/pjutil/pjutil.go
vendor/k8s.io/test-infra/prow/plugins/config.go
vendor/k8s.io/test-infra/prow/plugins/plugin-config-documented.yaml
vendor/k8s.io/test-infra/prow/pod-utils/decorate/podspec.go
vendor/modules.txt

Update test-infra to d2c24b2c8e3b

---

go.mod
go.sum
vendor/k8s.io/test-infra/prow/plugins/config.go
vendor/modules.txt

Update test-infra to c1043ab1c1ff

---

pkg/bugzilla/bugzilla.go

Reverts openshift/release-controller#312

Revert "bugzilla: comment on bugs"

---

cmd/release-controller/bugzilla.go

The bugzilla syncer occassionally fails after verifying bugs because it
fails to update the tag's annotations due to the imagestream being out
of date. This PR changes the behavior to pull the latest version of the
target imagestream before updating annotations to make sure it is up to
date.
/cc @bradmwilliams @stevekuznetsov

bugzilla: get latest imagestream before annotation update

---

go.mod
go.sum
vendor/modules.txt

Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>

update the test-infra vendors

---

pkg/bugzilla/bugzilla.go

This PR adds new verification requirements that QE wants as described in
DPCR-99.

bugzilla: add new verification requirements

---

cmd/release-controller/bugzilla.go
pkg/bugzilla/bugzilla.go

Reverts openshift/release-controller#338

Revert "bugzilla: improvements to auto-verification for QE"

---

go.mod
go.sum
vendor/k8s.io/test-infra/prow/config/config.go
vendor/k8s.io/test-infra/prow/flagutil/strings.go
vendor/k8s.io/test-infra/prow/plugins/config.go
vendor/modules.txt

Prerequisite for https://github.com/openshift/ci-tools/pull/2462
[DPTP-2577](https://issues.redhat.com/browse/DPTP-2577)

Bump test-infra to 74a5a2f770f3

---

pkg/bugzilla/bugzilla.go

This improves the comment made when a bug is not moved to `VERIFIED` due
to the bug not being in the correct `ON_QA` status, which should not
happen, but can occassionally occur if the ART bot does not change the
status of the bug in a timely manner after triggered a new nightly.
Resolves OCPCRT-111.

bugzilla: modify handling of ON_QA error message

---

cmd/release-controller-api/main.go
cmd/release-controller/main.go

This PR implements liveness and readiness checks using prow's health
utils.

main: add proper health checks to both command

---

cmd/release-controller-api/main.go

This PR adds the `port` flag to replace the `listen` flag. The `listen`
flag is currently retained to prevent breaking existing deployments and
can be removed once all deployments have removed the `listen` flag from
their arguments.

release-controller-api: use listen port instead of listen address

---

pkg/bugzilla/bugzilla.go

The semver library requires the micro/patch version to be an integer,
and the bugzilla target release can have `z` as in the patch location.
This PR manually splits and parses the target release to fix this.

bugzilla: fix target release parsing

---

.ci-operator.yaml
Dockerfile
images/release-controller-api/Dockerfile
images/release-controller/Dockerfile

.ci-operator.yaml,Dockerfile: use golang 1.17

---

cmd/release-controller-api/controller.go
cmd/release-controller-api/http.go
cmd/release-controller-api/http_helper.go
cmd/release-controller-api/main.go
cmd/release-controller/controller.go
cmd/release-controller/main.go
cmd/release-controller/sync.go
cmd/release-controller/sync_verify.go
pkg/release-controller/release.go

Reverts openshift/release-controller#362

Revert "sync_verify: run e2e tests on stable releases"

---

cmd/release-controller-api/controller.go
cmd/release-controller-api/http.go
cmd/release-controller-api/http_helper.go
cmd/release-controller-api/main.go
cmd/release-controller/controller.go
cmd/release-controller/main.go
cmd/release-controller/sync.go
cmd/release-controller/sync_verify.go
pkg/release-controller/release.go

Reverts the revert of #362 and fixes an implementation issue that was causing out of range errors. The fix is in a separate commit to make review easier.

Reimplement stable e2e testing with bug fixed

---

pkg/release-controller/release.go

This PR changes the logic for determining the tests to run on stable
imagestreams to instead choose all required non-aggregate jobs from the
corresponding nightly and run them as informing jobs on the stable.

release-controller/release.go: change stable verification test logic

---

go.mod
go.sum
vendor/k8s.io/test-infra/prow/bugzilla/client.go
vendor/k8s.io/test-infra/prow/bugzilla/types.go
vendor/k8s.io/test-infra/prow/github/client.go
vendor/k8s.io/test-infra/prow/plugins/BUILD.bazel
vendor/modules.txt

Required by https://github.com/openshift/ci-tools/pull/2726

bump test-infra to v0.0.0-20220315203149-843d26549556

---

pkg/cmd/release-payload-controller/cmd.go
pkg/cmd/release-payload-controller/job_state_controller.go
pkg/cmd/release-payload-controller/job_state_controller_test.go
pkg/cmd/release-payload-controller/payload_accepted_controller.go
pkg/cmd/release-payload-controller/payload_rejected_controller.go
pkg/cmd/release-payload-controller/prowjob_controller.go
pkg/releasepayload/jobrunresult/helpers.go
pkg/releasepayload/jobstatus/helpers.go
pkg/releasepayload/jobstatus/helpers_test.go
pkg/releasepayload/releasepayloadstatus/helpers.go
pkg/releasepayload/releasepayloadstatus/helpers_test.go

Refactoring JobStatus methods
Adding JobRunResult helpers and test
Adding aggregate_state_controller logic
Refactoring status to releasepayloadstatus
Enabling the Aggregate State Controller

Adding the Aggregate State Controller

---

cmd/release-controller/bugzilla.go
cmd/release-controller/jira.go
pkg/release-controller/release_info.go

Revert the temporary fix on the Bugzilla verifier and add the `--skip-bug-check` to  `oc adm release`.

Add `--skip-bug-check` for bug-listing

---

cmd/release-controller/jira.go
pkg/jira/jira.go

Fix wrong metric configuration on Jira Verifier (copy-paste issue).

jira verifier: fix metrics configuration

---

hack/release-tool.py

This PR adds the ability to prune release `imagestreamtags` from any of the release imagestreams.  One or more tags may be specified and their respective confirmation and deletions will be handled individually.  
The usage is as follows:
If the `--execute` flag is not specified, then the script will run in `dry-run` mode:
```
$ ./hack/release-tool.py prune 4.12.0-0.nightly-2022-07-31-235028
[2022-08-03 12:06:13,509] [dry-run] Deleting imagestreamtag: ocp/release:4.12.0-0.nightly-2022-07-31-235028
[2022-08-03 12:06:13,510] You must specify "--execute" to permanently apply these changes
```
If `--execute` is specified, then the user will be prompted to confirm the deletion before any actions are taken:
```
$ ./hack/release-tool.py --execute prune 4.12.0-0.nightly-2022-07-31-235028
Delete: …
```

Adding a prune option to the release-tool

---

hack/release-tool.py

Releases with the `release.openshift.io/keep` annotation are supposed to be preserved from GC, by the release-controller, and therefore shouldn't be able to pruned either.  This PR adds the necessary protection, to the release-tool, to prevent pruning any releases with the "keep" annotation.

Preventing pruning releases flagged as `keep`

---

pkg/jira/jira.go

This PR fixes a few things on the Jira Verifier:
- The returned value of `fileds.status.Name` is "Verified" for the  REST API, while we check for "VERIFIED" here. 
The status checks are changed to be case-insensitive. 
- Log the `issue.Key` instead of `issue.ID`, since the Key is the visible part on Jira (ID is used by the backed only). 
- Change the status update to use the UpdateStatus method.
- Remove a few TODO-s, since they are verified by now.

fix on Jira Verifier

---

cmd/release-controller/main.go

This PR makes the main function add bugzilla and github secrets to the secret agent. While some flagutils add the secret to the agent before creating the client, bugzilla doesn't, which causes auth to not work at all. This PR fixes that by adding all tokens that are not added to the secretAgent automatically.

main: add secret agent to fix bugzilla authentication

---

cmd/release-controller/bugzilla.go
cmd/release-controller/jira.go

Bugs/issues annotation fails intermittently (due to changes under the process). 
This PR adds a retry loop before returning an error and creating the Failed Annotation metric.
At the current state, the sync loop is handling the retry, but we are creating failed_annotation metrics on every failure, which generates an alert (unnecessarily).
With this change, the metric is created after retrying a few times, which should fix the rate of unnecessary alerting.

retry the ImageStream annotation when the RV is outdated

---

hack/release-tool.py

Adding an `archive` option to the `release-tool` that can be used to archive all respective releases, from a specified `X.Y` version prefix, from the release-controller's `release` imagestream.  The script performs the following steps:
1. Constructs a new imagestream, named: `<release namespace>/<release imagestream>-archive-<prefix>`, that contains all the tags that have valid `from:` definitions (i.e. releases from quay.io).  
1. Creates the imagestream
1. Patches in the remaining tags, with "local" status.tags values (i.e. pointing to the local repository).
1. Deletes the tags, one at a time, from the release imagestream.
The command can be executed as follows:
``` bash
```
* Specifying the `--execute` option will enable to script to persist its changes on cluster.  No changes will be …

Adding the ability to archive obsolete tags

---

cmd/release-controller-api/http_compare.go
cmd/release-controller-api/static/releaseDashboardPage.tmpl
cmd/release-controller-api/static/releasePageHtml.tmpl

https://issues.redhat.com/browse/FDN-166

Link to a basic guide on OpenShift release types

---

hack/release-tool.py

To force the re-import of tags of the `ocp/4.13-art-latest` imagestream, you can run:
``` bash
$ ./release-tool.py import 4.13-art-latest
```
To force the re-import of tags of the `ocp-s390x/4.13-art-latest-s390x` imagestream, you can run:
``` bash
$ ./release-tool.py -a s390x import 4.13-art-latest
```

Adding the ability to re-import tags when they are wedged

---

cmd/release-controller/bugzilla.go
cmd/release-controller/jira.go
pkg/release-controller/release_info.go
pkg/release-controller/release_info_test.go

`oc adm release info` output has changed (the ID field changed to a string, instead of an Int).

fix on bugs/issues verification

---

cmd/release-controller-api/http.go
cmd/release-controller-api/http_changelog.go
cmd/release-controller-api/http_compare.go
cmd/release-controller/sync.go
go.mod
go.sum
pkg/release-controller/release_info.go
pkg/release-controller/types.go
pkg/rhcos/rhcos.go
vendor/github.com/opencontainers/go-digest/.mailmap
vendor/github.com/opencontainers/go-digest/.pullapprove.yml
vendor/github.com/opencontainers/go-digest/.travis.yml
vendor/github.com/opencontainers/go-digest/CONTRIBUTING.md
vendor/github.com/opencontainers/go-digest/LICENSE
vendor/github.com/opencontainers/go-digest/LICENSE.docs
vendor/github.com/opencontainers/go-digest/MAINTAINERS
vendor/github.com/opencontainers/go-digest/README.md
vendor/github.com/opencontainers/go-digest/algorithm.go
vendor/github.com/opencontainers/go-digest/digest.go
vendor/github.com/opencontainers/go-digest/digester.go
vendor/github.com/opencontainers/go-digest/doc.go
vendor/github.com/opencontainers/go-digest/verifiers.go
vendor/modules.txt

This is the second attempt at adding the support for rendering the changelog in JSON.

OCPCRT-74: redux

---

cmd/release-controller-api/http.go

I'm working on a bot that can notify us when z-streams go for some period of time w/o an accepted payload, and as part of that it would be useful to be able to distinguish between "no payloads being attempted" and "no payloads being accepted", hence the proposal of these new apis.

Add releasestream endpoints for rejected releases and all releases

---

pkg/rhcos/rhcos.go

Updating the links to the new and improved RHCoS Release Browser

Updating the RHCoS Release Browser links

---

pkg/rhcos/rhcos.go
pkg/rhcos/rhcos_test.go

Changes based on the comment here: https://github.com/openshift/release-controller/pull/497#issuecomment-1435122741

Updating RHCoS release browser logic

---

cmd/release-controller-api/http.go
pkg/release-controller/release_info.go

To determine the ticket's status at the time of the build, check its transitions. If the status at that point was `on_qa`, `verified`, or `modified`, the ticket will be considered `IncludedInBuild`.

featureInfo: include on_qa, verified, modified to Complete section

---

pkg/jira/jira.go
pkg/jira/jira_test.go

Comment on the merged PR(s) after a nightly/release is created.

Comment on PRs after nightly/release

---

pkg/release-controller/release_info.go

To, hopefully, help thwart the thundering herd problem we have if/when the git cache gets wiped, I'm adding an InitContainer that will perform either of the following operations based on the contents of the mounted PVC volume:
1. Prime a newly created PVC with an initial changelog from the latest `4-stable` and `4-dev-preview` releases (takes roughly 12 minutes)
2. Perform git maintenance on **all** the existing repositories that are present on the PVC (takes roughly 8 minutes)

Adding an initContainer for the git cache

---

hack/bot_comments_cleaner.py

Adding a clean-up script for Jira comments, In case we would need to clean Bot comments in bulk again in the future.

add a Jira cleanup script

---

cmd/release-controller/jira.go

The existing logic silently swallows any errors when creating a `StableRelease` against a `Stable` imagestream, because the `Name`  (i.e. `release` or `4-dev-preview`) is not a valid `SemanticVersion`.  This basically caused the comparison logic to always fail and return `X.Y.0`.  This PR changes the functionality to extract the tag for the "first GA Release" (i.e. X.Y.0) from the `StableRelease` streams.  It then performs a date comparison between the GA Release and the current tag's `CreationTime`.

Updating FixVersion logic to apply X.Y.z when necessary

---

pkg/jira/jira.go
pkg/jira/jira_test.go

This PR enables the Jira verification logic to interrogate an Issues pre-populated `Versions`, if they exist, and then verifies if the `FixVersion`, we intend to use (i.e. X.Y.z), is part of that list.  If so, then it will always default to using that version.  If not, it will check if a version prefixed with `openshift-` exists (i.e. openshift-X.Y.z).  If so, then it will use that version instead.

Determine `FixVersion` based on Issues's Versions

---

cmd/release-controller/sync_verify_prow.go

Since also agent jobs are using ofcir

Override cluster allocation for agent jobs

---

hack/release-tool.py

Figured it was time to automate the ability to add/delete/list release imagestreamtags with the "keep" annotation.  This annotation can be applied to any release to prevent both the release-controller and the release-tool.py script from inadvertently deleting the release.  This annotation should be used sparingly because keeping releases around long term will inevitably cause us to hit the etcd size limit of the release imagestream.
The idea here is if/when ART/TRT/Staff Engineers/etc reach out to us to prevent garbage collecting (aka pruning) a specific release, we can set this flag and it will be safe from "our" usual methods of clean up.  Once the specified release has passed whatever milestone (like promoting a nightly to an RC), it's then safe to remove the annotation and purge the …

Adding support for applying the Keep annotation

---

pkg/cmd/release-reimport-controller/controller.go

This also adds some new logging to the reimport controller

reimport-controller: add verbosity to klog calls

---

cmd/release-controller-api/http.go

Before, we were finding Image Streams with [ReleaseAnnotationConfig](https://github.com/openshift/release-controller/blob/21d1a69e3d51bd8411556d870e9b8eeb5c7f0db5/pkg/release-controller/release.go#L83). Those include only `4.y-art-latest`. Our goal is to find the Streams that are specific for a nigthly, which does not have `ReleaseAnnotationConfig`. But it does have the field `ReleaseAnnotationReleaseTag`.

[OCPCRT-169] Report build specific inconsistencies instead of only the latest

---

OWNERS

add myself to the `approvers` list

---

cmd/release-controller-api/http.go
cmd/release-controller-api/static/featureRelease.html
pkg/release-controller/release_info.go

/hold
Currently, I can't identify a release that includes a ticket with a Demo link, hence I can't include a screenshot of how it should look (it will look the same as the other collapsible elements, like the `View the Description` one).

Add Demo links on `Feature Based` release page

---

pkg/release-controller/release_info.go

We'd like to try and figure out who, if anyone, is using the files cache...
If we hear back from anyone who has a legitimate usage for this cache, then we'll consider ways to improve/migrate/etc.  If not, then we'll probably turn it off (and wait for people to scream).

Asking for input from users of the Files Cache

---

cmd/release-controller/sync_verify_prow.go

Reverts openshift/release-controller#600

Revert "TRT-1504: Pin gcp release jobs to gcp build clusters"

---

hack/release-tool.py

Add command to modify team approval state labels for release payloads.

release-tool.py: add approval subcommand

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/prow/pkg/github/client.go
vendor/sigs.k8s.io/prow/pkg/plugins/config.go

needed for https://github.com/openshift/ci-tools/pull/4339

update prow dependency

---

hack/release-tool.py

Inform ART about the reverted image so that the revert can persist across updates: https://github.com/openshift-eng/art-tools/pull/975

Adding sticky revert annotation and poke

---

go.mod
go.sum
vendor/modules.txt
vendor/sigs.k8s.io/prow/pkg/bugzilla/client.go
vendor/sigs.k8s.io/prow/pkg/config/config.go
vendor/sigs.k8s.io/prow/pkg/config/jobs.go
vendor/sigs.k8s.io/prow/pkg/config/tide.go
vendor/sigs.k8s.io/prow/pkg/genyaml/genyaml.go
vendor/sigs.k8s.io/prow/pkg/kube/prowjob.go
vendor/sigs.k8s.io/prow/pkg/plugins/plugins.go

Bumping Prow

---

cmd/release-controller-api/http.go

disable the feature analysis endpoint and remove the link in the UI

---

pkg/release-controller/release_info.go

Limit the concurrency to 1 call per second, using a simple time ticker. Set the chunk size to the maximum allowed, to limit API calls as much as possible.

limit the jira concurrency calls

---

cmd/release-controller/sync_analysis.go
cmd/release-controller/sync_upgrade.go
cmd/release-controller/sync_verify.go
pkg/release-controller/types.go

/cc @bradmwilliams @AlexNPavel
/hold 
https://github.com/openshift/ci-tools/pull/4505

Configure label for capability for dispatcher/scheduler

---

pkg/cmd/release-mirror-cleanup-controller/cmd.go
pkg/cmd/release-mirror-cleanup-controller/controller.go

Add a minimum age for tags to be deleted by the mirror-cleanup controller. Default is 30 days and it is configurable via a flag.

release-mirror-cleanup-controller: add minimum age

---

cmd/release-controller-api/http_changelog.go

Change the loading alert to an `alert-info` so it renders in blue to match the changelog one.
Always flush after printing the "Node Image Info" heading so that the anchor is valid earlier during the render. Also, don't wait 1s to print the info alert so users can tell earlier that work is happening. If the result is cached, the box will never be visible anyway since it gets hidden so quickly.

http_changelog: simplify node image info render logic

---

pkg/release-controller/release_info.go

The files-cache is being inundated with requests for EOL releases.  There must be some sort of automation that is just cycling through versions somewhere and it's killing the cache.  This PR puts a hard block in against downloading anything prior to `4.11`.
Hopefully, whomever/whatever is wanting this information will step forward when this merges.

[files-cache] Prevent downloading anything earlier than 4.11

---

pkg/jira/jira.go
pkg/jira/jira_test.go

This PR adds the initial support for interrogating the pre-merge verification labels attached to the external PR's associated with a respective release's Jira tickets.

Adding initial support for pre-merge verification labels

---

pkg/jira/jira.go

Add `MODIFIED` as an allowed state for the jira verifier.

jira: allow MODIFIED issues to be moved to VERIFIED

---

pkg/jira/jira.go
pkg/jira/jira_test.go

During my testing of the `/verified` functionality, I observed a few weird interactions when working on Issues that have more than 1 PR associated with them...
If/when the release-controller encounters an Issue, that contains multiple PRs, it will set the `FixVersion` and comment on the issue once the very first PR merges.  After that, it will no longer process this Issue because the `FixVersion` has already been set.
This PR changes the behavior such that the release-controller will comment on an Issue whenever any of the associated PR(s) have merged and been included into an Accepted release:
`Feature partially included in release <version>`.
Once all the associated PRs have been merged and included into an Accepted release, the comment will change to: `Feature included in release …

Improve logic around Issues with multiple linked PRs and setting FixVersion

---

go.mod
go.sum
vendor/github.com/cloudflare/circl/ecc/goldilocks/curve.go
vendor/github.com/cloudflare/circl/sign/ed25519/point.go
vendor/github.com/ulikunitz/xz/TODO.md
vendor/github.com/ulikunitz/xz/lzma/header.go
vendor/github.com/ulikunitz/xz/lzma/reader.go
vendor/github.com/ulikunitz/xz/lzma/writer.go
vendor/modules.txt

Bumps based on govulncheck reports

vendor: bump modules with patched vulnerabilities
