- cmd/release-controller/sync.go
Makes it more accessible and ensures the images are pullable by the same
clients.
> Create the mirror in the release namespace

- cmd/release-controller/controller.go
- cmd/release-controller/main.go
- cmd/release-controller/release.go
- cmd/release-controller/sync.go
- cmd/release-controller/types.go
We will push origin and ocp releases to separate image streams.
> Take the target image stream as an argument rather than hardcode

- cmd/release-controller/controller.go
- cmd/release-controller/main.go
- cmd/release-controller/release.go
- cmd/release-controller/sync.go
- cmd/release-controller/types.go
Only process image streams in the release namespace.  This was causing panics when testing on the api.ci cluster because neither controller could see the release tags the others create that were referenced by the prow jobs in the ci namespace.
Because ProwJobs are shared, we can see triggers in other namespaces that
we won't be able to access. Only queue the release namespace.
Also, clean up the mirror so that we can make it match our output. Mirror should be `<source>-<date>` so that it sorts with the source
name    = v4.0 
source  = origin-v4.0 
mirror  = origin-v4.0-20180919010102
tag     = v4.0-20180919010102 
promote = v4.0
> Ensure controllers don't fight over shared prow jobs

- cmd/release-controller/http.go
- cmd/release-controller/sync.go
- cmd/release-controller/types.go
- pkg/prow/apiv1/types.go
We write the verification status eagerly, using a new 'Pending' state
to represent jobs in progress. Avoid calling update if we make no
changes to a tag. Report the pending state in the release status page.
> Report links immediately instead of after job runs

- cmd/release-controller/release.go
- cmd/release-controller/sync.go
- cmd/release-controller/types.go
Slightly simplify how tags are synced. Ensure disabled jobs aren't
considered as incomplete.
> Sync all verification jobs, not just the first

- README.md
On general principle of repositories should have useful README.md
files.  Let's just point to the existing docs in the release repo.
> README.md: New file

- cmd/release-controller/graph.go
CVO and Cincinnati v1 reverted to using generic 'payload'.
> Switch back to 'payload' in the fake image graph

- cmd/release-controller/main.go
- cmd/release-controller/release.go
- cmd/release-controller/sync.go
- cmd/release-controller/types.go
Allow the contents of the release to be set on another image stream
at the end of the run. Will allow 'openshift/origin-v4.0' to be kept
in sync with 'ocp/4.0'
> Support publishing an image stream after verification

- cmd/release-controller/http.go
Display a loading banner at 500ms, an error at 10s, fallthrough to
the generic layout, and tweak styles.
> Show partial progression when changelogs are being generated

- cmd/release-controller/http.go
- cmd/release-controller/info.go
- cmd/release-controller/main.go
- cmd/release-controller/release.go
Mount the `git-credentials` secret from the release job namespace
into the pod for use with cloning protected repos.
Load the most recent tagged 'tests' image from the first release
stream in the release namespace (4.0.0-0.ci for release-ocp) and
update it every few hours to avoid having to periodically update
the operator.
> Mount secrets in for accessing protected repositories

- cmd/release-controller/http.go
- cmd/release-controller/info.go
- cmd/release-controller/sync.go
If the hash changed between our read and write times the job would hang.
Instead, fill the hash after we mirror.
Fix a wierd failure to fetch.
> Set the release tag input hash *after* we mirror

- cmd/release-controller/sync.go
- cmd/release-controller/types.go
Use the last Accepted release tag as RELEASE_IMAGE_INITIAL if a job
requests it. Optional jobs can fail without forcing the tag to be Rejected.
Upgrade jobs will have special semantics in a future change that will
verify edges besides the defaults.
> Add support for optional and upgrade verify steps to a payload

- cmd/release-controller/controller.go
- cmd/release-controller/http.go
- cmd/release-controller/http_helper.go
- cmd/release-controller/http_helper_test.go
- cmd/release-controller/main.go
- cmd/release-controller/prow.go
- cmd/release-controller/sync.go
- cmd/release-controller/types.go
- cmd/release-controller/upgrades.go
Track information from upgrade prowjobs and display them in the graph.
Shows visual connections between graph elements. Does not persist the
graph at the current time.
> Display the upgrade graph alongside the list

- cmd/release-controller/http.go
We sometimes peak around 12 concurrent updates
> Tighten the upgrade cell width for more upgrades

- cmd/release-controller/http.go
- cmd/release-controller/http_helper.go
They are likely pruned and don't add value to the list
> Remove tags that look internal from the external list

- cmd/release-controller/http.go
- cmd/release-controller/http_helper.go
- cmd/release-controller/upgrades.go
Reorder changelog to better reflect priority - tests and upgrades,
then changelog. Make the connection between upgrades and changelog
clearer.
> Link upgrade graph links to the details page

- cmd/release-controller/http.go
- cmd/release-controller/http_helper.go
- cmd/release-controller/main.go
- cmd/release-controller/prow.go
- cmd/release-controller/sync_verify.go
- cmd/release-controller/types.go
- cmd/release-controller/upgrades.go
In order to keep state across multiple restarts, periodically snapshot the
upgrade graph state to a Kube secret and restore from it on startup. The
graph is gzipped (which is why we use a secret). A future commit should
prune / sort the graph to make it easier to restore.
Add `/archive/graph` to let a client dump the graph.
> Save and restore upgrade graph state to a secret

- cmd/release-controller/controller.go
- cmd/release-controller/main.go
- cmd/release-controller/release.go
- cmd/release-controller/sync.go
- cmd/release-controller/sync_gc.go
- cmd/release-controller/types.go
The explicit `to` field allows one controller to manage multiple
flows. For now we anticipate a single release stream, but in the
future it may make more sense to split. Use an annotation on the
target to trigger some kinds of resync. Rename the secret.
> Require image streams to declare a target to publish releases to

- cmd/release-controller/http.go
- cmd/release-controller/sync.go
- cmd/release-controller/sync_gc.go
- cmd/release-controller/sync_publish.go
- cmd/release-controller/types.go
Add `tags` to the `imageStreamRef` publishing type to indicate only
a subset of tags should be published when the release is Accepted.
Update the overview page to clarify publishing rules, but make the
message override all generated description text instead of being
additive.
Prune completed jobs after 2 hours.
> Support promoting only a subset of tags on success

- cmd/release-controller/sync_tags.go
Side effect of collapsing stable and target into the same location.
> Only tags in the stable release are 'next' candidates

- cmd/release-controller/sync_release.go
- cmd/release-controller/sync_tags.go
- cmd/release-controller/types.go
Stable imports need to keep pull specs accurate. On import use
`oc adm release mirror --to-image-stream` to do that. Allow a
user to force rebuilding the payload to point to the mirror if
they set `release.openshift.io/mirrorImages` on the incoming tag
(mostly for CI use cases).
> Importing a tag should preserve the pull location of the tag

- cmd/release-controller/http.go
Now that cluster-bot can kick upgrade jobs, report multiple results for
each upgrade edge.
> Show multiple upgrade results

- cmd/release-controller/sync_verify_prow.go
- pkg/prow/apiv1/agent.go
- pkg/prow/apiv1/consts.go
- pkg/prow/apiv1/jobspec.go
- pkg/prow/apiv1/load.go
- pkg/prow/apiv1/podspec.go
- pkg/prow/apiv1/types.go
Pull in incrementally more of the prow object and copy more code.
Still not including periodics/postsubmits. This will allow us to pull
from a config map directory, not just a single file.
> Support prow directories by refreshing prow config

- cmd/release-controller/http.go
- cmd/release-controller/http_helper.go
- cmd/release-controller/info.go
The latest release for a stream is now accessible via HTTP at
/releasestream/{release}/latest
which redirects to the details page. The URL
/releasestream/{release}/latest/download
redirects to artifacts (if specified).
The API URL
/api/v1/releasestream/{release}/latest
returns a JSON object with name, pull spec, and download link.
---
Indicate when the download has failed due to expired content
Remove DOWNLOADING.md and write FAILING.md. Also return a Retry-After 
header for clients.
---
Indicate location of source code in footer
---
Includes #72
> Expand API suggestions and make user links easier.

- cmd/release-controller/audit.go
- cmd/release-controller/main.go
Allow us to be absolutely sure about the content we run.
> Run `oc` locally with `--audit-cli-image=local`

- cmd/release-controller/audit.go
- cmd/release-controller/sync.go
Pending was only used in the specific case of looking up an init
container message, whereas here we want only Failed pods.
> Grab termination message from failed pods, not pending pods

- cmd/release-controller/http_upgrade_graph.go
Allow someone to filter edges like the official channels will.
> Add additional prerelease-* and nightly-* handlers

- cmd/release-controller/http.go
- cmd/release-controller/http_helper_test.go
When we picked up a newer semver, https://github.com/blang/semver/issues/55
caused other releases to be ignored from the comparison drop down.
For now work around that by double parsing (tolerant and normal)
the release name to see if it's stable. Also include the stable tags
which are also not semver valid.
> Correctly include other releases as compare targets

- cmd/release-controller/http_helper.go
- cmd/release-controller/http_helper_test.go
If a tag has both an internal From and an external From upgrade
edge (4.1.0-0.ci-xxxx AND 4.1.0-rc.5) the first internal edges are
lost.
Correct the logic that ignored the first set of internal edges and
add unit tests.
> External edges cause some upgrade edges to be omitted visually

- cmd/release-controller/http_helper.go
- cmd/release-controller/http_helper_test.go
This method did not work at all
> Fix another bug in external name splitting

- cmd/release-controller/http.go
So I can link directly to them with [this][1] and similar.
[1]: https://openshift-release.svc.ci.openshift.org/releasestream/4-stable/release/4.1.0-rc.6#upgrades-from
> cmd/release-controller/http: Add id anchors to "Upgrades from" and "Upgrades to"

- cmd/release-controller/main.go
- cmd/release-controller/upgrades.go
- cmd/release-controller/upgrades_test.go
The previous version of UpgradesFrom included entries from other versions
incorrectly, which meant the upgrade graph appeared to show more results
than actually appeared.
Fix the display logic to only include upgrades in the 'Upgrades to' list if
they actually come from this version.
Also, sync upgrade graph (read-only) in dry-run so the graph is complete
for debugging problems.
> Only show upgrades to entries once in the details page

- cmd/release-controller/http.go
1 week is too imprecise, use minutes/hours/days/weeks longer.
> Extend relative time intervals for better precision

- cmd/release-controller/http.go
So I can link directly to them with [this][1] and similar.  I considered adding a prefix to avoid possible conflicts with other IDs, but our existing names:
```console
$ curl -s https://openshift-release.svc.ci.openshift.org/ | sed -n 's|.*>\([^<]*\)</h2>.*|\1|p'
4.1.0-0.ci
4.1.0-0.nightly
4.2.0-0.ci
4.2.0-0.nightly
4-stable
```
suggest the names are unique enough on their own, so I haven't used a prefix.
[1]: https://openshift-release.svc.ci.openshift.org/#4-stable
> cmd/release-controller/http: Add id anchors to image streams

- cmd/release-controller/release.go
- cmd/release-controller/sync_verify.go
- cmd/release-controller/sync_verify_prow.go
- cmd/release-controller/types.go
Previously on stable jobs we picked the latest accepted tag which
resulted in a 4.1 job upgrading from a 4.2 rc. Instead, define an
upgradeFrom type of Previous (uses last accepted), PreviousMicro
(uses last stable in same minor), and PreviousMinor (uses last stable
in previous minor). Clarify what the upgrade job runs.
> Upgrade jobs should have a defined strategy for selecting source

- cmd/release-controller/sync_verify.go
> Upgrade from stable should default to PreviousPatch, not PreviousMinor

- cmd/release-controller/http.go
- cmd/release-controller/sync.go
Busy image streams would not hit this, but rarely used image streams
wouldn't trigger when the interval was up. For sanity, just queue.
Add log info output to the rate limit code so we know what release
was queued while debugging.
> sync: Requeue when rate limited to avoid waiting forever

- cmd/release-controller/sync.go
We have to process pending tags, we just want to gate new images.
> sync: Don't clear pending tags when rate limiting

- cmd/release-controller/sync_publish.go
The processing was dropping existing spec tags that are in the
exclude list instead of preserving them, causing the ci-operator to
fail to build a release.
> publish: Do not delete the target spec tag if it is excluded

- cmd/release-controller/sync.go
The delay logic was checking the newest possible tag, instead of the newest
tag for a release. This caused all releases to delay on each other, rather
than being independent.
Add the tag we are delaying on to the log message to make debugging easier.
> sync: Use the first tag in the current release to check date

- cmd/release-controller/main.go
- cmd/release-controller/release.go
- cmd/release-controller/sync_gc.go
Currently changelogs are generated by with the image under the "tests"
tag in the first image stream that has a release definition. This
results today in 4.1 being used. Instead, let a flag specify which
tools image to use `--tools-image-stream-tag=4.4:tests` which will
fix a few changelog errors. Use the old behavior if not specified.
Prevent a stable image stream from accidentally being used (it won't
have a tests image).
> Allow controllers to pick which image to use for changelog generation

- cmd/release-controller/info.go
- cmd/release-controller/main.go
The multi-arch folks reached out about the release-controller not supporting their respective installer downloads when accessing the Release Status webpage. This PR adds support for the files-cache to pull the installers from their architecture specific release-namespace.
> Files cache multi arch

- cmd/release-controller/http.go
- cmd/release-controller/http_helper.go
- cmd/release-controller/main.go
Each link under the "upgrades from" column goes to the job that ran the upgrade test.
Note that if we ran a particular upgrade multiple times, it is represented multiple times (the from version is repeated once for each attempt).
example of "release failing" warning:
> add a buildcop dashboard for upgrade jobs

- Makefile
- cmd/release-controller/http_helper_test.go
Unittests are currently broken, which we never noticed because the `unit` ci operator ends up executing [`make test`](https://github.com/openshift/release/blob/e75d84a8ff9c9393beb6b80e1e508b6906fea59a/ci-operator/config/openshift/release-controller/openshift-release-controller-master.yaml#L35) which is undefined, which `make` consider a reason to happily return:
```
$ make test
make: Nothing to be done for 'test'.
alvaro@t470s-[2020-03-19-15:22]:[master][2]~/.../openshift/release-controller
$ echo $?
0
```
/assign @smarterclayton
> Fix unittests

- cmd/release-controller/http.go
- cmd/release-controller/http_helper.go
- cmd/release-controller/types.go
Sort the index page by stable releases, then releases in descending
semantic order. Ensure "ci" sorts before "nightly". Add a new "hide"
boolean to releases that puts them at the bottom of the page.
When more than 3 jobs are pending or failed, summarize them and link
to the details status page instead of listing them. Hide successful
results from the page.
> Reorganize the release index page

- Makefile
- cmd/release-controller/controller.go
- cmd/release-controller/main.go
- cmd/release-controller/sync_verify_prow.go
- cmd/release-controller/sync_verify_prow_test.go
- go.sum
With this change it is possible to set up a distinct cluster for ProwJob resources, which we will need once we migrate the prow controlplane to a different cluster.
/assign @smarterclayton @stevekuznetsov
> Seperate job build cluster

- cmd/release-controller/http.go
- cmd/release-controller/http_helper.go
- cmd/release-controller/release.go
- cmd/release-controller/types.go
Returns tags within that stream, supports `phase=` filter and
shows all tags by default.
> Add a stream api endpoint /api/v1/releasestream/{name}/tags

- cmd/release-controller/http.go
- cmd/release-controller/http_candidate.go
- cmd/release-controller/http_upgrade_graph.go
- cmd/release-controller/release.go
- cmd/release-controller/sync.go
- cmd/release-controller/sync_tags.go
- cmd/release-controller/sync_verify.go
Fix the release stream tags api to return sorted tags.
> Update naming of release tag accessors to avoid bugs with sorting

- OWNERS
- cmd/release-controller/main.go
This is an intermediate PR that changes the variable name of `flag` to `flagset` in the main function and adds new flags for the bugzilla and github clients that will be added via #151. It is necessary to add them in a separate PR because the changes from #151 will result in the release-controller crashing if it is not provided the flags. This PR allows us to make the required changes to the running deployments ahead of time.
> main: add new flags

- cmd/release-controller/controller.go
The bugzilla queue was only get imagestreams with `releaseAnnotationConfig` set when it should have been getting ones with `releationAnnotationSource` instead.
> controller: queue bugzilla for is with releaseAnnotationSource

- cmd/release-controller/info.go
The "release" image stream, for multi-arch's, has an extension...
release-s390x
release-ppc64le
This PR adds support for the extensions to the files-cache.
> Adding support for multi-arch release streams with extensions

- cmd/release-controller/info.go
Copy and paste error when moving python code into go.  This PR converts the tabs back into spaces.  I have verified that the code runs successfully in our test environment.
> Converting tabs to spaces for python code

- cmd/release-controller/bugzilla.go
Using just `tag.Name` (as used in `sync.go`) results in the following error:
```
I0527 20:16:11.174903       1 glog.go:58] Failed to generate bug list: command terminated with exit code 1
$ oc adm release info --bugs=/tmp/git/ --output=name 4.1.0-0.nightly-2020-05-23-080652 4.1.0-0.nightly-2020-05-24-040147
error: the semantic version "4.1.0-0.nightly-2020-05-23-080652" is not present in the cluster version status or in the official versions list, cannot be resolved
```
This PR changes the bugzilla sync function to use the public docker repo version of the image instead, similar to the way the web interface works.
> bugzilla: use public docker image repo for releaseInfo.Bugs

- cmd/release-controller/http.go
The overview dashboard displays an alert message:
`This release has no recently accepted payloads, investigation required.`
when the number of non-terminal releases exceed the `maxUnreadyReleases` parameter.  The logic that calculates whether this message is displayed or not, does not take into account releases that are in a **Ready** state.
https://bugzilla.redhat.com/show_bug.cgi?id=1841350
> Bug 1841350: Ignore releases in Ready state when calculating maxUnready

- cmd/release-controller/info.go
- cmd/release-controller/info_test.go
This fixes issues where `strconv.Atoi` was throwing errors due to being passed an empty string. I originally thought this was occurring for releases that had no bugs and returned an empty string, and I handled that in an earlier PR, but that wasn't the main issue. 
Before `string` -> `[]int` handling was moved to `info`, the bugzilla pkg would handle `Atoi` errors by adding the error to the `errs` list and then continuing. This error wasn't getting properly get logged before, so we never saw it, and the rest of the bugs would be processed as normal. This masked the strconv errors when presented with an empty string, which would happen at the end of each bug list since the ouptut of `oc adm release info --bugs=... --output=name` always ends in a newline. This handles that and adds a unit …
> info: ignore empty bugs after string split

- cmd/release-controller/bugzilla.go
This allows us to handle all tags that were created before we added this feature and also allows us to requeue if the imagestream update at the end of the function fails to update the annotations.
> bugzilla: requeue imagestream if non-verified tags are found

- pkg/bugzilla/bugzilla.go
Sometimes people ignore the bot and manually change the bugzilla tags, resulting in a bug not being linked. Just log the offending bugs without returning an error.
> bugzilla: ignore nonlinked bugs

- cmd/release-controller/bugzilla.go
The queue ignores keys being added that are already in the queue. When adding to the queue inside `syncBugzilla`, we want the function to be rerun. Using `AddAfter` with a 1 second delay should be enough to fix this.
> bugzilla: use AddAfter instead of Add inside syncBugzilla

- cmd/release-controller/controller.go
- cmd/release-controller/http.go
- cmd/release-controller/http_compare.go
- cmd/release-controller/http_helper.go
The initial impression of the release comparison dashboard was quite positive.  The one piece of feedback we received was to possibly add a link to it from the main page, so it's easier to get to.  This PR adds a "Quick links" section under the main title of each of the primary pages...
Home Page:
Overview Dashboard
Comparison Dashboard
> Adding a Quick links section to the primary pages

- cmd/release-controller/http.go
- cmd/release-controller/sync.go
Fixing this...
I like how https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/#4.5.0-0.nightly says **Next release may not start: no more than 2 pending** when there are 3 pending.
> Making the number of unready release match the configured value of maxUnreadyReleases

- cmd/release-controller/bugzilla.go
- cmd/release-controller/bugzilla_test.go
- cmd/release-controller/types.go
This commit allows us to configure a release tag to compare against
when we are trying to verify bugs for the oldest release in an image
stream.
> bugzilla: add previousReleaseTag field to verifyBugs in config

- cmd/release-controller/audit.go
- cmd/release-controller/audit_backend_gcs.go
- cmd/release-controller/main.go
Fix a bug where newer GCS clients reject an empty precondition object
(because 0 and default serialization are the same) by explicitly stating
DoesNotExist. Also ensure options is passed to the client to pick up the
command line credentials (which was always broken).
After these changes signatures are uploaded to GCS using the service
account path correctly.
> audit: Fix audit with latest GCS client and correct an argument bug

- pkg/bugzilla/bugzilla.go
There are some bugs that have an unusual permissions issue that results
in the bugzilla client failing to get external bugs. This commit is a
workaround for that issue that just logs the error instead of returning
it, allowing the release to move into the `bugs-verified` state instead
of looping indefinitely.
> bugzilla: workaround for permissions issue with certain bugs

- cmd/release-controller/http.go
- cmd/release-controller/http_helper.go
- cmd/release-controller/info.go
I have forked the changes that Ankita has put forth in #163 and addressed all of the concerns that were raised during review as well as made some minor enhancements to the UI and some of the `newestSemVer` logic.
We received a request to provide a visual indication of upgrades, that have not been tested, for the release admins to potentually take action upon (https://issues.redhat.com/browse/DPCR-25).  These changes gather the list of baked-in upgrades and compares them against the results of the know upgrade tests.  If any upgrades are not accounted for, they are listed in a warning box on the release detail page.
The noticeable UI changes appear when upgrades, that are included in the release info, are missing from the list of Upgrades From  list on release detail pages:
```
$ oc adm …
```
> Adding information about baked in upgrades to the release detail pages

- cmd/release-controller/http.go
This PR is to add a nil check around the "Untested upgrades" warning block to prevent it from showing up when there are no untested upgrades.  Found while navigating here:
https://openshift-release.apps.ci.l2s4.p1.openshiftapps.com/releasestream/4-stable/release/4.5.0-rc.3
> Adding nil check to prevent Untested upgrades block from always showing up

- cmd/release-controller/http_changelog.go
- cmd/release-controller/info.go
It was pointed out that the architecture specific links to RHCOS content were
all pointing to the x86_64 streams and therefore presenting incorrect information
to the users.  These changes extract the architecture out from the ReleaseInfo 
payload for the specified release. Once the archtecture is known, it is
used to create the correct URL to the architecture specific content and RHCOS
difference tool.
> Adding support for architectures for RHCOS linking

- cmd/release-controller/http.go
It was observered that the "Updates from:" label had gone missing on
a couple of release pages and that some releases were missing their
upgrade results all together.  This fix addresses both of these issues.
Both issues were caused by the ReleaseInfo not containing any "Previous"
upgrade information.
> Upgrade related UI fixes

- cmd/release-controller/sync.go
- cmd/release-controller/sync_tags.go
- cmd/release-controller/sync_verify.go
TransitionTime field is used to track completion time of the previous run of a job to decide when a retryable job should be scheduled for run again. This was not being removed on terminal tags, causing release tag annotation sizes to increase, approaching the 2MB annotation size limit. This fix removes the field from the statuses of all terminal tags, and adds a syncTerminal loop to strip any existing terminal release tags of the field.
These changes supersede PR #166 and also contain a fix that enables the logic to work as expected.
> Remove transitionTime field in terminal releases to reduce annotation sizes

- cmd/release-controller/sync.go
- cmd/release-controller/sync_tags.go
These changes remove the syncTerminal loop that was introduced in #213 to
cleanup the transitionTime entry in all of the releases in terminal states.
> Removing sync terminal loop

- cmd/release-controller/main.go
This PR adds a github throttle flag to limit the maximum number of
requests the GitHub client (used by the bugzilla verifier) can make per
hour.
> main: add github throttle flag

- pkg/bugzilla/bugzilla.go
This PR changes the behavior of the bugzilla verifier to only move the
bug to the VERIFIED state if that bug has the correct status as
configured in the bugzilla plugin for `state_after_merge`.
> bugzilla: only move bug to VERIFIED if in correct merged state

- pkg/bugzilla/bugzilla.go
A previous PR changed the behavior to only verify bugs in the
`state_after_merge` state.  Since there is automation that changes the
status to `ON_QA` once a bug is in a nightly build, `ON_QA` should be
used as the allowed status instead.
> bugzilla: use ON_QA as allowed status for verification

- cmd/release-controller/http.go
- cmd/release-controller/http_compare.go
Per JIRA ticket: https://issues.redhat.com/browse/DPCR-38
We have been requested to update our pages with a banner that indicates:
a) This site is part of OpenShift's continuous delivery pipeline and
only builds obtained directly from access.redhat.com or try.openshift.com
are considered GA OCP builds
b) Tested upgrade paths recorded in this site do not represent OCP
supported upgrade paths. Only those upgrade paths available via either
the fast or stable OpenShift Update Service (Cincinnati) channels are
supported by Red Hat.
These changes update the various pages as follows:
1. Release Status
2. Release Dashboard
3. Release Comparison Dashboard
4. Release Stream
> Adding an unsupported banner to the release-controller pages

- cmd/release-controller/main.go
- cmd/release-controller/periodic.go
- cmd/release-controller/sync_verify.go
- cmd/release-controller/types.go
- vendor/k8s.io/test-infra/prow/cron/BUILD.bazel
- vendor/k8s.io/test-infra/prow/cron/cron.go
- vendor/modules.txt
This PR adds support for the release-controller to run periodics defined
in release configs, similar to verify jobs. It uses the test-infra cron
pkg and has a similar structure to prow's horologium sync function, but
modified to use the data structures, interfaces, and configuration that
the release-controller has.
To add a periodic job, a user would add the job to the `periodic`
section of the release config with the name of the job, the interval or
cron timing the user wants, and an `upgrade` bool and `upgradeFrom`
string if it is an upgrade job.
Previously, release informers (specifically upgrades) were run by
horologium and used curl to get release tags and annotated themselves to
be picked up by release-controller. This PR allows us to fix that
problem by creating the prowjobs …
> cmd: add support for running periodics in release-controller

- cmd/release-controller/periodic.go
- cmd/release-controller/sync_verify.go
- cmd/release-controller/types.go
This adds the `PreviousMinus1` upgrade type, which is the second latest
accepted tag for an image stream. This will be the default upgradeType
for upgrade periodics, which use the latest accepted tag as
`RELEASE_IMAGE_LATEST`.
> types: add PreviousMinus1 upgrade type

- cmd/release-controller/config_validate.go
- cmd/release-controller/config_validate_test.go
- cmd/release-controller/main.go
- go.mod
This PR adds a config validation mode to the release-controller that can
be run with the `--validate-configs` flag, which takes the directory
containing the configs as its value. It is intended to be run as a
presubmit in `openshift/release`. At the moment, it verifies that all
the release configs can be unmarshalled and does verification on the
periodic job configs. More verification functions can be added to it in
the future to validate that other parts of the release configs are valid
as well.
> cmd: add config validation mode

- cmd/release-controller/info.go
Someone reached out in slack stating that they were unable to download the
installer for a specific release.  Upon further investigation, it turns out
that there was a bug in the FileServer logic when handling the exceptions that
allow for the retrying of the downloads.  The specific error was:
```
File "/tmp/serve.py", line 67, in do_GET
print("Unable to get release tools for %s: %s" % name, e.output)
TypeError: not enough arguments for format string
```
The fix is to enclose the values in parenthesis.
> Files-cache messaging format fix

- cmd/release-controller/info.go
After #228 was deployed, the files-cache was able to make more progress
downloading installers.  Unfortunately, the logic that interrogates the errors
from oc, is using the old (python2) style strings and the errors that are
returned are binary strings.  This PR updates the logic to compare the strings
as binary and also adds another check for an updated message format.
> Files-cache exception handling fix

- cmd/release-controller/sync_mirror.go
Recently the release-controller has been struggling with images where
the `.status.tag` was ahead of the `.spec.tag`.  The logic in this PR
expected that these 2 values should be equal.  The fix is to error when
the `.spec.tag` is greater than the `.status.tag`.
> Updating ImageStream comparison logic

- cmd/release-controller/periodic.go
- cmd/release-controller/sync_verify_prow.go
This PR changes the behavior of the release-controller to always set the
`RELEASE_IMAGE_INITAL` env var for upgrade release jobs.  Previously, it
would only do this if the job contained the env var in its job spec,
which means that any generated upgrade job would not be able to properly
be run by release-controller. This also means that upgrade jobs
configured to be run by release-controller would not be able to be
rehearsed, as the required empty `RELEASE_IMAGE_INITIAL` in the
rehearsal would cause the ci-operator incorrectly set the pullspec to an
empty string.
> [DPTP-1797] sync_verify: always set RELEASE_IMAGE_INITIAL for upgrades

- cmd/release-controller/periodic.go
This was causing release-controller to skip jobs configured via cron instead of interval.
> periodic: only set interval duration if interval != ""

- cmd/release-controller/controller.go
- cmd/release-controller/main.go
- cmd/release-controller/sync_tags.go
- cmd/release-controller/types.go
The actual delete will be done by DPTP-CM: https://github.com/openshift/ci-tools/tree/master/cmd/dptp-controller-manager
We can revert this after migration of CI-Registry is done.
/hold
Wait for the deleting implementation with DPTP-CM.
https://github.com/openshift/ci-tools/pull/1483
/cc @stevekuznetsov @alvaroaleman
> Annotation: release.openshift.io/soft-delete

- cmd/release-controller/release.go
In some cases, we see an ImageStream before the OCP controller manager
has been able to populate it's public image repository URL in the
status. We cannot use this ImageStream yet as we do not know from where
to pull images in this stream. Just wait and re-queue later.
> controller: don't process ImageStreams without a repo

- cmd/release-controller/http_helper.go
When the pending/failing link was updated last, failing was used for
both instead of pending. Update so that pending count is correct.
> http: Count of pending jobs was incorrect

- cmd/release-controller/http.go
- cmd/release-controller/http_helper.go
- cmd/release-controller/main.go
It has grown far too large to show and is no longer visually useful. Users
probably use a subset graph view (possibly via an inline short link in the
future).
> http: Don't show upgrade graph in stable streams

- cmd/release-controller/http_helper_test.go
- cmd/release-controller/main.go
- cmd/release-controller/periodic.go
- cmd/release-controller/sync_verify_prow.go
- cmd/release-controller/types.go
- cmd/release-controller/upgrades.go
- cmd/release-controller/upgrades_test.go
Introducing the `release.openshift.io/architecture` annotation to be applied to all the prowjobs created by the release-controller. 
This annotation will eventually be used to filter prowjobs, by their respective architecture, prior to inserting data into the upgrade graph.
> Adding the 'release.openshift.io/architecture' annotation to prow jobs

- cmd/release-controller/main.go
Now that both the release-controller and the ci-chat-bot are adding
the `release.openshift.io/architecture` annotation to their prowjobs,
we can prevent updating the release-upgrade-graph with jobs that do
not correspond to the architecture specified to the release-controller.
> Only add upgradeResults for the specified architecture

- cmd/release-controller/http.go
This all recently changed and there's a lot of confusion about it;
it's not obvious that `registry.ci.openshift.org` is backed by
`app.ci`, etc.
This is an alternative/supplement to https://github.com/openshift/ci-docs/pull/118
> Add a link to the app.ci cluster login on the page

- cmd/release-controller/controller.go
- cmd/release-controller/http.go
- cmd/release-controller/main.go
@vrutkovs  has requested the ability to remove the following message from the
UI for the OKD release-controller:
`Pulling these images requires authenticating to the app.ci cluster.`
This PR switches the existing logic around to accept a message to display, when necessary, for authenticating to a registry.  The message can be enabled by specifying the following option: `--authentication-message`
The current logic can be achieved by specifying the following:
```
--authentication-message="Pulling these images requires <a href=\"https://docs.ci.openshift.org/docs/how-tos/use-registries-in-build-farm/\">authenticating to the app.ci cluster</a>."
```
> Adding the ability to specify the CI Auth message on the commandline

- cmd/release-controller/config_validate.go
- cmd/release-controller/config_validate_test.go
- cmd/release-controller/main.go
A new field has been added to ci-operator that adds a label to jobs to
define them as release-controller jobs. This reduces confusion when
defining jobs in ci-operator configs that are supposed to be executed
periodically or as verification by release-controller.
This PR adds validation to make sure that all jobs defined as periodics
or verification in release-controller have the correct label on the job
config, and all job configs with the label are exist in the
release-controller configs.
> validate: add validation for release informing jobs

- cmd/release-controller/sync_verify_prow.go
This PR fixes an issue where ci-operator would fail to start a job as it
would try to pull a non-existant release based on the `releases`
configured in the ci-operator config. This situation could occur on
creation of a new release or when many tags fail to be accepted and only
1 accepted tag exists for a release. To fix this, we configure
release-controller to always set the initial release image to override
what is defined in the ci-operator config.
> sync_verify_prow: always set an initial release

- cmd/release-controller/sync.go
- cmd/release-controller/sync_analysis.go
- cmd/release-controller/sync_release.go
- cmd/release-controller/sync_verify.go
- cmd/release-controller/sync_verify_prow.go
- cmd/release-controller/types.go
- cmd/release-controller/upgrades.go
This PR is to enable the changes that @deads2k is working towards for release analysis.  Currently, these changes will have no impact until a new "analysis" stanza is added to a release's release configuration.
An example entry looks like:
```
"analysis": {
"upgrade": {
"upgrade": true,
"optional": true,
"prowJob": {
"name": "periodic-ci-openshift-release-master-nightly-4.9-e2e-aws-upgrade"
},
"analysisJobCount": 2
}
}
```
The analysis entries are just `ReleaseVerification` blocks that support a new optional parameter: *analysisJobCount*
If not specified, the *analysisJobCount* defaults to executing: *10* instances of the specified job.  There is currently a hardcoded maximum limit, of 20 jobs that can be executed concurrently.  
The prowjobs that are created by this process have the …
> Release analysis jobs

- cmd/release-controller/info.go
- cmd/release-controller/main.go
I have been setting up an environment, on the DPCR cluster, to allow us to test changes, to the release-controller, on.    This PR will allow the release-controller to be run, successfully, on another cluster without having to make any changes to the code.  This can be accomplished by adding the `--registry` option and specifying the name of the registry to use, instead of the default: `registry.ci.openshift.org`.
> Changes to allow relocation to any cluster without changing code

- cmd/release-controller/main.go
The DPTP folks have opened [DPCR-80](https://issues.redhat.com/browse/DPCR-80) for us to address the fact that the release-controller is frequently unavailable.  Part of the request is that we should add readiness and liveness probes.  This PR adds 2 endpoints to facilitate these probes.
> Adding simple /healthz and /healthz/ready endpoints

- .ci-operator.yaml
- Dockerfile
The ci-operator config allows for a `from-repository` build-root image definition.  A follow up PR in `openshift/release` will enable these changes and then we'll only have to update a single location if/when switching Golang versions in the future.
> Sync Dockerfile and ci-operator config

- cmd/release-controller/bugzilla.go
- cmd/release-controller/controller.go
- cmd/release-controller/main.go
- vendor/github.com/prometheus/client_golang/prometheus/promauto/auto.go
- vendor/modules.txt
This PR adds a CounterVec that increments a counter for important error
encountered in the `syncBugzilla` function. Each count has a `type`
label, which will make it easier to identify which part of the function
is encountering the error, which should make debugging quicker.
/cc @stevekuznetsov @bradmwilliams
> bugzilla: add error metrics

- cmd/release-controller/bugzilla.go
- cmd/release-controller/main.go
In order for alerts based on errors to function, values must be set for
the countervec labels. This PR sets all labels used for bugzilla errors
to 0 when bugzilla verification is enabled.
> bugzilla: initialize and set bugzilla error metrics on start

- pkg/bugzilla/bugzilla.go
This PR adds functionality to comment on bugs when doing verification
stating why a bugs has been moved to VERIFIED (or not).
> bugzilla: comment on bugs

- cmd/release-controller/sync.go
- cmd/release-controller/sync_analysis.go
- cmd/release-controller/sync_verify.go
- cmd/release-controller/sync_verify_prow.go
- cmd/release-controller/types.go
This PR refactors the Analysis Verification Job definitions to be part of the `verify` stanza.  This eliminates the need for the `analysis` stanza all together.  The reason that this was done was to enable the release-controller to:
1. Launch the specified number of Analysis jobs
2. Launch the aggregator job with the necessary information for the analysis jobs
I have also added a new field `AggregateProwJob` to the `ReleaseVerification` struct to allow for an override to the default aggregator job name (`release-openshift-release-analysis-aggregator`) defined as a [step](https://steps.ci.openshift.org/reference/openshift-release-analysis-aggregator) in the ci-operator config.
> Adding support for launching analysis aggregator job

- cmd/release-controller/main.go
The client used by the release-controller for in-cluster configs is set
up to automatically reload in-cluster configs periodically without
needing to change how it is currently configured in the
release-controller. This means that the watch on the token file's path
that triggered periodic restarts when the bound token was updated can be
removed.
/cc @stevekuznetsov @bradmwilliams
> main: do not reload on in cluster token change

- cmd/release-controller/cluster_distribution.go
- cmd/release-controller/cluster_distribution_test.go
- cmd/release-controller/controller.go
- cmd/release-controller/main.go
- cmd/release-controller/sync_verify_prow.go
Recently, it has been observed that certain failures are happening on one of the build clusters, but not on another.  It has been requested that instead of the weekly re-balancing of the release-controller jobs (that CI performs), we perform a random rollout of the various release verification jobs to the configured build clusters.  This PR adds the ability to specify "cluster groups", on the commandline, and when defined the release-controller we distribute the release verification jobs out, to the respective group, randomly.
For instance, using the current configuration as reference, we'll need to define 2 cluster groups:
` --cluster-group build01,build02 --cluster-group vsphere`
When the release-controller reads in the prowjob definition, it will check if the defined `cluster:` value …
> Adding random distribution support for build clusters

- cmd/release-controller/types.go
Now that #310 has merged, we can cleanup these unnecessary fields.
> Removing analysis block and analysisJobCount

- pkg/bugzilla/bugzilla.go
This PR reimplements the commenting feature originally added in #312 and
later reverted due to unintended spamming. This adds a check to prevent
spamming where it loads all comments for the bug and verifies that an
identical comment has not already been made.
/cc @bradmwilliams @stevekuznetsov
> bugzilla: reimplement bugzilla commenting

- cmd/release-controller/audit.go
- cmd/release-controller/bugzilla.go
- cmd/release-controller/bugzilla_test.go
- cmd/release-controller/config_validate.go
- cmd/release-controller/config_validate_test.go
- cmd/release-controller/controller.go
- cmd/release-controller/http.go
- cmd/release-controller/http_candidate.go
- cmd/release-controller/http_helper.go
- cmd/release-controller/http_helper_test.go
- cmd/release-controller/http_upgrade_graph.go
- cmd/release-controller/main.go
- cmd/release-controller/periodic.go
- cmd/release-controller/prow.go
- cmd/release-controller/release.go
- cmd/release-controller/sync.go
- cmd/release-controller/sync_analysis.go
- cmd/release-controller/sync_check.go
- cmd/release-controller/sync_gc.go
- cmd/release-controller/sync_mirror.go
- cmd/release-controller/sync_publish.go
- cmd/release-controller/sync_release.go
- cmd/release-controller/sync_tags.go
- cmd/release-controller/sync_verify.go
- cmd/release-controller/sync_verify_prow.go
- cmd/release-controller/types_test.go
- cmd/release-controller/upgrades.go
- cmd/release-controller/upgrades_test.go
- pkg/release-controller/types.go
- pkg/release-controller/utils.go
Having all the release-controller types buried underneath the release-controller prevents other tools from utilizing the various types.  This PR moves the `cmd/release-controller/types.go` file up into `pkg/release-controller`, Exports the various pieces, and updates all the code to utilize the new `release-controller` package.
> Refactoring types.go out into common place

- cmd/release-controller/bugzilla.go
- pkg/bugzilla/bugzilla.go
QE has recently asked to simplify the requirements for the bugzilla
autoverification back to just the LGTM by QA contact requirement.
Another request was to clarify that, after this message is sent, the QA
contact must manually move the bug to `VERIFIED` themselves.
This resolves OCPCRT-110.
I also added the release with the bugfix to the comment, as I believe
that could be useful and it is a simple addition.
> bugzilla: improvements to auto-verification for QE

- cmd/release-controller/bugzilla.go
- pkg/bugzilla/bugzilla.go
PR #338 was reverted due to a bug that was crashlooping the
release-controller. The bug was a nil pointer dereference on the
`bug.QAContactDetail` field. This PR reimplements #338 and adds a check
for the field to make sure it is not nil before dereferencing it.
> bugzilla: reimplement #338 with nil reference fix

- cmd/release-controller/release.go
Increase the per release config limit to 12k to allow slighly larger release configs for CI jobs.  This is a one time bump and future increases need to be done elsewhere.
> Increasing the 8k limit, on ReleaseConfigs, to 12k

- cmd/release-controller/controller.go
- cmd/release-controller/http.go
- cmd/release-controller/http_candidate.go
- cmd/release-controller/http_changelog.go
- cmd/release-controller/info.go
- cmd/release-controller/main.go
- cmd/release-controller/sync.go
To handle the existance of manifest list based releases, we need to call an `oc image info` with a `--filter-by-os` option to get the respective `digest` value that can be used to call `oc adm release info` where needed.  Unfortunately, this means we have to make 2 calls down into the `git-cache` pod, so it does take a bit more time for things like the changelog.
> Adding support for manifest list based releases

- cmd/release-controller-api/main.go
- cmd/release-controller/main.go
- cmd/release-controller/sync_verify.go
- pkg/release-controller/cache.go
- pkg/release-controller/prowjob.go
This PR adds upgrade graph loading to the `release-controller-api`
binary.
> release-controller-api: load upgrade graph

- cmd/release-controller-api/http.go
- cmd/release-controller/http.go
- pkg/release-controller/types.go
Currently ART is using the `/api/v1/releasestream/{release}/latest` API to determine whether the release being promoted is accepted by the release controller.
This method has some timing issues when ART attempts to rerun some automation for an old release.
It would be very convenient to query the `Phase` field for a specific release with the `/api/v1/releasestream/{release}/release/{tag}` API.
With this power, ART's automation will be smarter and idempotent.
> Include `phase` field in the release info API

- pkg/bugzilla/bugzilla.go
This PR fixes an issue where the release-controller would comment that
all linked bugs have beenn approved and that the release-controller will
move the bug to VERIFIED when the bug has already been moved to
VERIFIED.
> bugzilla: properly ignore already verified bugs

- pkg/bugzilla/bugzilla.go
- pkg/release-controller/semver.go
This PR adds a check to the bugzilla verifier that makes sure that the
target release of the bug being verified matches the target release of
the bug.
> bugzilla: check bug target release before verifying

- cmd/release-controller-api/controller.go
- cmd/release-controller-api/http.go
- cmd/release-controller-api/http_helper.go
- cmd/release-controller-api/main.go
- cmd/release-controller/controller.go
- cmd/release-controller/main.go
- cmd/release-controller/sync.go
- cmd/release-controller/sync_verify.go
- pkg/release-controller/release.go
This PR adds support for identifying what major point release a stable
release is part of and then running a required `e2e` and `e2e-serial`
test configured for the point release on the stable release.
> sync_verify: run e2e tests on stable releases

- cmd/release-controller-api/http_helper.go
This is a minor visual fix to prevent empty "Pending jobs" lists in
stable releases created before the stable e2e testing feature was added.
> http_helper: remove empty "Pending jobs" lists

- .ci-operator.yaml
- images/release-controller-api/Dockerfile
- images/release-controller/Dockerfile
PR https://github.com/openshift/release/pull/25971 adds the controller
binaries as inputs for the image. This PR updates the Dockerfiles to
make use of the new inputs.
> images: simplify dockerfiles

- pkg/bugzilla/bugzilla.go
This PR adds proper handling for bugs that do not have a set target
release at time of verification.
> bugzilla: handle unset target releases

- hack/release-tool.py
The `release-tool.py` makes it easy for anyone, with the correct permissions, to `accept` or `reject` release payloads.
Running the command without the `--execute` parameter will output the updated payload that would be applied to the system
To `accept` a release:
```
$ ./release-tool.py accept 4.10.0-0.nightly-2021-12-18-034942 --execute
```
To `reject` a release:
```
$ ./release-tool.py reject 4.10.0-0.nightly-2021-12-18-034942 --execute
```
All the default values can be overwritten by specifying the appropriate options to the `release-tool`:
```
Openshift Configuration Options:
-c CONTEXT, --context CONTEXT
The OC context to use (default is "app.ci")
-n NAMESPACE, --namespace NAMESPACE
The namespace prefix to use (default is "ocp")
-i IMAGESTREAM, --imagestream IMAGESTREAM
The name of …
```
> Adding release-tool for TRT

- cmd/release-controller/main.go
- cmd/release-controller/prune_graph.go
- pkg/release-controller/upgrades.go
Adding a couple commandline options to prune, and verify, the release-upgrade-graph.  Calling the release-controller like:
`./release-controller --release-namespace ocp --job-namespace ci --prune-graph`, will fetch all the tags from the `release` imagestream.  Then it finds the tags that are NOT present in either of the `TO` and `FROM` upgrade graphs.  Then, it generates the union of the 2 lists, and prunes the graph accordingly.  Lastly, by default, it will pretty print the resultant graph for verification.  Optionally, you can also specify the `--print-secret-payload` option to print out the base64 output of the compressed graph.
> Adding a commandline graph pruner

- cmd/release-controller-api/http_helper.go
The two warnings being removed are essentially permanently
displayed on the release controller today.
'Some tags are significantly older ...' - This is expected as upstream
changes slow. CI may rebuild images for various reasons, but ART
will not. This is permanent in the case where a release goes EOL.
'No downstream builds have been pushed ...' - ART's imagestream
is carefully curated and pruned with automation. It is limited
to release payload components. The CI imagestream is not pruned
and has collected images unrelated to the release payload.
> Remove unhelpful warnings from UI

- cmd/release-controller-api/http.go
- cmd/release-controller-api/http_helper.go
- cmd/release-controller-api/static/htmlPageEnd.html
- cmd/release-controller-api/static/htmlPageEndScripts.tmpl
- cmd/release-controller-api/static/htmlPageStart.html
- cmd/release-controller-api/static/releaseDashboardPage.tmpl
- cmd/release-controller-api/static/releasePageHtml.tmpl
- Fix the `4-stable` configuration issue (the stable table ID was hardcoded to `4-stable`, while the table ID can be different in different architectures). The scripts are now rendered in a loop, using the data from the release streams (using the information from "stream.Release.Config.As"). The streams are grouped by version for any stream that has a "Stable" tag.
- Move the HTML code from `http.go` to the `static` dir. 
- Remove the extend/collapse icon (+/-) when the number of rows is <= 5 (where 5 is the default number of rows displayed in a group) since it's not applicable.
> fix 4-stable grouping 

- cmd/release-controller-api/http.go
Remove the static configuration for the search bar. It's now activated for any release with `..Release.Config.As` equal to `Stable` (`releasecontroller.ReleaseConfigModeStable`)
> search bar bugfix

- pkg/release-controller/release_info.go
Increase the PVC size from 40Gi to 64Gi. The git-cache disk is often getting full. Normally the usage is always close to the 40Gi limit, often causing issues.
> increase the PVC size

- cmd/release-controller-api/http_upgrade_graph.go
The `shape="record"` has been deprecated with newer versions of Dot.  Although the command does succeed, it returns a `1` as it's exit code and we fail to generate `png` and/or `svg` representations of the upgrade graph.  Removing the entry clears the error code and we render the graph accordingly.
> Removing `shape="record"` from dot entries

- pkg/bugzilla/bugzilla.go
- pkg/bugzilla/bugzilla_test.go
When creating a comment (`CreateComment` method), the server returns a status 201 (created). 
The comment is created as expected in the ticket, but we do not handle the response properly (hence this is considered an error, while it is not).
> whitelist status codes for bugzilla responses

- cmd/release-controller/bugzilla.go
- cmd/release-controller/jira.go
- pkg/release-controller/release_info.go
When we introduced the Jira integration logic there were issues with the
integration with `oc` that are preventing us from being able to process
Bugs.  This fix reverts us back to the "old" logic and should allow for
the verification logic to resume.
This PR can be reverted if/when an appropriate fix is made in `oc`.
> Temporary fix to allow bugzilla verification to proceed

- pkg/bugzilla/bugzilla.go
More 401 errors biting us, this time on Updates.
> Handling the 401 error for bzClient.UpdateBug()

- cmd/release-controller/audit.go
- cmd/release-controller/bugzilla.go
- cmd/release-controller/jira.go
- cmd/release-controller/sync.go
- cmd/release-controller/sync_gc.go
I observed that in most cases there was a "begin" message, but never a corresponding
"end" message surrounding the various sync loops that occur.  It appears that this was
caused by the deferal of the recover() method followed, immediately, by a panic(nil).
I have updated the offending logic to only issue the panic() call when an error is
returned from the recover() logic.
> Updating the deferred recovery logic

- cmd/release-controller/jira.go
Bugfix on the generated issue list (`oc` striping `OCPBUGS-` from the issue `ID` string).
> jira verifier: append `OCPBUGS-` on the bug-list returned by `oc`

- cmd/release-controller-api/http.go
- cmd/release-controller-api/http_helper.go
Prune EOL releases from the drop-down selector on the release summary pages. 
The `forceRefresh=true` query parameter can be used to refresh the EOL list dynamically.
> prune `EOL` releases from the release summary page

- cmd/release-controller/controller.go
- cmd/release-controller/main.go
- cmd/release-controller/sync_release_payload.go
- cmd/release-controller/sync_release_payload_test.go
- cmd/release-controller/sync_tags.go
This PR will enable the `release-controller` to begin creating `ReleasePayload` objects whenever it creates a new release.  The `release-payload-controller` will then take over all processing of the ReleasePayloads.  The `release-controller` and the `release-payload-controller` will initially operate independently of each other and both should closely mirror reality, but ultimately the `release-controller` is still responsible for the overall acceptance/rejection of releases and is based on the imagestream annotations.
> Create ReleasePayloads whenever a new release is created.

- cmd/release-controller/audit.go
- cmd/release-controller/sync_gc.go
- cmd/release-controller/sync_release.go
We are currently orphaning Pods whenever we cleanup any of our Release Jobs.  This PR should instruct the Garbage Collector to also delete the underlying pods created by a Job.
> Cleanup pods from batch.v1 jobs

- pkg/release-controller/types.go
This PR is to prepare for the release-controller to automatically launch upgrade tests, for all know supported upgrade edges, on releases being promoted into a `Stable` stream.  This new stanza is to provide the necessary configuration that the release-controller will use to determine the set of cloud platforms, and their respective ProwJobs, to run the upgrade tests.
> Adding support for upgrade validation tests

- cmd/release-controller/sync.go
- cmd/release-controller/sync_upgrade.go
This PR adds the ability, for the release-controller, to automatically launch upgrade jobs, evenly distributed across our various clouds, for each of the `upgrades` defined in `Stable` releases.
The upgrade job definitions are part of the standard Release Configurations and will only be executed when defined for a `Stable` stream, like: https://github.com/openshift/release/blob/master/core-services/release-controller/_releases/release-ocp-4.y-stable.json
The upgrade jobs are defined in their own stanza, where the name is the cloud provider of the job and the prowjob should point to a valid `ci-operator` prowjob definition. 
For `release-ocp-4.y-stable.json`, the values will be:
```
"upgrade": {
"aws": {
"prowJob":{"name":"release-openshift-origin-installer-e2e-aws-upgrade"}
},  
"azure": …
```
> [OCPCRT-32] Launch supported upgrade jobs for Stable releases

- cmd/release-controller/sync_upgrade.go
- cmd/release-controller/sync_upgrade_test.go
This logic will scale down the number of support upgrade tests, performed by the release-controller, for `Stable` payloads by taking a sample of the upgrades as follows:
Currently, for 4.10.31, there are 55 `previous` upgrades:
``` bash
$ oc adm release info quay.io/openshift-release-dev/ocp-release:4.10.31-x86_64 -o json | jq '.metadata.previous'
[
"4.10.10",
"4.10.11",
"4.10.12",
"4.10.13",
"4.10.14",
"4.10.15",
"4.10.16",
"4.10.17",
"4.10.18",
"4.10.20",
"4.10.21",
"4.10.22",
"4.10.23",
"4.10.24",
"4.10.25",
"4.10.26",
"4.10.27",
"4.10.28",
"4.10.29",
"4.10.3",
"4.10.30",
"4.10.4",
"4.10.5",
"4.10.6",
"4.10.7",
"4.10.8",
"4.10.9",
"4.9.19",
"4.9.21",
"4.9.22",
"4.9.23",
"4.9.24",
"4.9.25",
"4.9.26",
"4.9.27",
"4.9.28",
"4.9.29",
"4.9.30",
"4.9.31",
"4.9.32",
"4.9.33",
"4.9.34", …
```
> Enabling sampling of the supported upgrade tests

- cmd/release-controller/sync_upgrade.go
- cmd/release-controller/sync_upgrade_test.go
This PR generates a unique seed based on the `supportedUpgrades` for a given release.  This provides repeatable ordering, of the generated jobs, to prevent us from launching jobs for all the possible variations that are *not* part of the `First/Last` samples for the `supportedUpgrades`.
> Ensuring repeatable random ordering

- pkg/jira/jira.go
- pkg/jira/jira_test.go
- vendor/k8s.io/test-infra/prow/github/fakegithub/fakegithub.go
- vendor/modules.txt
This PR adds an internal interface with the definition of methods used by the Jira-Verifier, to be able to use the GitHub FakecCient and the missing unit-test for `VerifyJira`.
> add unit tests for Jira Verifier 

- cmd/release-controller-api/main.go
- cmd/release-controller/main.go
In reviewing the kubeconfig watcher logic, I noticed that a couple of the kubeconfigs were not actually being watched.  This PR adds the missing kubeconfigs to the watcher.
> Updating kubeconfig watcher logic

- hack/requirements.txt
This PR adds a requirements.txt file for `release-tool`. 
The tool has a single requirement, but since there is another [openshift](https://pypi.org/project/openshift/) module on `pypi` (besides the [required](https://pypi.org/project/openshift-client/) one), it can be confusing.
> add a requirements file for `release-tool.py`

- cmd/release-controller/sync_mirror.go
- pkg/release-controller/types.go
ART has requested that we interrogate the inbound imagestreams for a specific set of Annotations and if/when present we carry them forward into the release mirror that the release-controller creates.  This PR adds the necessary support as well as the list of currently supported Annotations:
1. `release.openshift.io/build-url`
2. `release.openshift.io/runtime-brew-event`
3. `release.openshift.io/inconsistency`
> Adding support for carrying ART annotations forward

- pkg/jira/jira.go
- pkg/jira/jira_test.go
This PR changes the behavior of the jira verification to not comment if an error is encountered getting issue labels from github. It also contains various changes and improvements to the jira_test file.
> jira: don't comment on github errors

- cmd/release-controller-api/http.go
- cmd/release-controller-api/static/htmlPageEndScripts.tmpl
The search breaks if there are multiple stable streams (all stable streams are grouped by the version) since the `elementID` and the function name are redeclared.
> bugfix on the search function (UI)

- pkg/releasepayload/utils/release-verification-job-details.go
- pkg/releasepayload/utils/release-verification-job-details_test.go
The `4-dev-preview` releases have not been processing their prowjobs appropriately because the logic was not aware of the `ec` naming convention.
> Adding support for parsing `EC` releases

- pkg/jira/jira.go
- pkg/jira/jira_test.go
This PR changes the behavior of the jira verifier to ignore all issues that are not marked as `ON_QA` in jira. This previous behavior was legacy functionality that was done due to an issue in ART's automation that would mark bugs in Bugzilla as `ON_QA` very late, causing the issue to be ignored by the `release-controller`. The release-controller would make a comment so it was clear that the problem was not from the `release-controller` side. A side-effect is that this can cause the `release-controller` to make incorrect comments on bugs where not all PRs have merged. This shouldn't be an issue anymore, so the `release-controller` will now assume that all bugs are marked as `ON_QA` promptly.
> OCPCRT-174: pkg/jira: ignore issues not ON_QA

- pkg/releasepayload/utils/release-verification-job-details.go
- pkg/releasepayload/utils/release-verification-job-details_test.go
The latest code is unable to parse the names of prowjobs, for the automatically generated upgrade jobs, that go from a Candidate release to a Candidate release, like:
`4.12.0-rc.0-upgrade-from-4.11.0-rc.9-aws`
This PR adds the necessary support for parsing those names.
> Adding support for Candidate to Candidate upgrade-from jobs

- cmd/release-controller-api/http.go
- pkg/release-controller/types.go
Reverting the `changeLog` API back to be the original base64 encoding of the HTML changelog and adding a `changeLogJson` API that contains the changelog in JSON.
> Fixes to get Sippy back up and operational

- pkg/release-controller/release_info.go
For reasons unknown at present, the change-log JSON may sometimes be incomplete. 
As of now, we are not performing any validation on the returned data. This incomplete data is being cached indefinitely, leading to this error message: `unexpected end of JSON input`, when the JSON is processed later on.
> Validate JSON change log

- pkg/releasepayload/utils/release-verification-job-details.go
- pkg/releasepayload/utils/release-verification-job-details_test.go
The release-payload-controller has been struggling to determine which job results to attribute certain prowjobs to.  Specifically, retry and multi-arch jobs.  Unfortunately, this means that we have been missing updates for some time.  This change should address the issues that I have observed most recently.
> Fixing version parsing logic (again)

- cmd/release-controller/sync_tags.go
In looking through the logs, I observed unexpected messages like:
`Mirroring release images in ocp/4.11 to ocp/4.114.9.9`
followed eventually by a corresponding:
`Error syncing {ocp 4.11}: mirror hash for "4.9.9" does not match, release cannot be created`
and lastly:
`Event(v1.ObjectReference{Kind:"ImageStream", Namespace:"ocp", Name:"4.11", UID:"a50994e1-06bf-4949-9e5a-3fce657b6f58", APIVersion:"image.openshift.io/v1", ResourceVersion:"2792915688", FieldPath:""}): type: 'Warning' reason: 'UnableToProcessRelease' mirror hash for "4.9.9" does not match, release cannot be created`
This lead to the discovery of a handful of extra imagestreams like:
```
4.144.9.9
4.134.9.9
4.124.9.9
<and so on>
```
It turns out that the existing logic always returned the "last" `is.spec.tag`.  This worked …
> Fixing broken imagestreamtag generation logic

- cmd/release-controller-api/http.go
Removing the unused `{release}` URL parameter for `apiFeatureInfo` and `httpFeatureInfo`.
A bugfix on Epics without feature status and another one fixing duplicated entries caused by improperly removing elements from the `featureTrees` slice.
> feature info: remove unnecessary URL parameter

- cmd/release-controller-api/http.go
Included in this PR: 
- Removed unnecessary keys from the API. 
- Removed the `ResolutionDate` from the `FeatureTree` since it is not needed. 
- Renamed one of the keys on FeatureTree.
> feature info: remove unnecessary fields from the api

- cmd/release-controller/sync_verify.go
- cmd/release-controller/sync_verify_test.go
Since there are now 2 "Stable" release streams, the latest minor/patch version selected for upgrades was random between the 2 streams. This patch fixes the logic to choose the latest between the 2 and makes a new function to share the logic for PreviousMinor and PreviousPatch.
> sync_verify: fix minor and patch version selection

- cmd/release-controller-api/http.go
- cmd/release-controller-api/http_test.go
This PR fixes an issue caused by the `4-dev-preview` imagestream when finding the last minor for the `New features` feature. It also simplifies the code significantly.
> http: fix and simplify nextMinor function

- pkg/jira/jira.go
- pkg/jira/jira_test.go
Add a comment on tickets that are manually moved to `Verified`. 
If a ticket is `verified` but does not contain a comment from the bot, the bot will add one.
Including a few improvements to the code as well (mostly nits).
> jira Verifier: comment manually verified ticket

- cmd/release-controller/controller.go
- cmd/release-controller/legacy_results.go
- cmd/release-controller/legacy_results_test.go
- cmd/release-controller/main.go
- cmd/release-controller/sync_release_payload.go
- cmd/release-controller/sync_release_payload_test.go
This PR adds a sync loop to the release-controller to process `Stable` release `imagestreamtag`s that do not have a corresponding `ReleasePayload`.  The loop will only run when enabled by adding the `--process-legacy-results` flag to the commandline.  If enabled, the logic will run immediately and then every 6 hours thereafter.  The expectation is that this process only needs to run once, but it shouldn't hurt if it continues to run.
> Legacy Results Processing

- cmd/release-controller/legacy_results.go
Looking through the results, I noticed that for imagestreams that were being skipped, we were not saying why. :(
> Adding errors to message output

- cmd/release-controller-api/controller.go
- cmd/release-controller-api/http_helper.go
- cmd/release-controller-api/main.go
- pkg/release-controller/release_info.go
- pkg/releasepayload/utils.go
- pkg/releasepayload/utils_test.go
This PR switches the UI's data source, for the results of the release verification jobs, from the ImageStream Annotations over to the ReleasePayloads.
While testing this out, I ran into a Panic caused because I was not specifying the Jira endpoint parameters in my local sessions.  I've added a couple line to prevent the panic and pop an error to the screen.  This really shouldn't even happen, but just in case!
> Adding ReleasePayload support to the UI

- pkg/cmd/release-payload-controller/job_state_controller.go
- pkg/cmd/release-payload-controller/job_state_controller_test.go
For any individual job, there should always be at least a single JobRunResult.  Retries are consecutive attempts of the initial job that ended in a failure state.  Therefore, the maximum number of JobRunResults should amount to 1 + job.MaxRetries.
> Fixing logic that determines the aggregate state of JobRunResults

- cmd/release-controller-api/http_helper.go
- cmd/release-controller-api/main.go
- cmd/release-controller/main.go
- cmd/release-controller/sync_verify.go
- pkg/cmd/release-payload-controller/legacy_job_status_controller.go
- pkg/release-controller/prowjob.go
- pkg/release-controller/prowjob_test.go
- pkg/release-controller/types.go
To free up a little space in the release imagestreams (about 20%) we are going to truncate the ProwJob URLs down to just their unique paths.  This PR adds support for writing the truncated URLs to the imagestream annotations as well as re-hydrating whenever they are referenced in the UI.
> Truncate ProwJob URLs

- pkg/release-controller/release_info.go
The git-cache is full, causing failures in loading change logs. Increasing the size to 200Gi, from 128Gi.
> increase the git-cache PVC size

- pkg/release-controller/release_info.go
Ran into an issue where the git maintenance was failing and I couldn't tell which repo was being processed.  Printing out the repo name to assist in debugging init issues.
> Echo repo name while performing git repo maintenance

- cmd/release-controller/jira.go
While we wait for a resolution to the inconsistencies found with the `Fix Version` field in the `OCPSTRAT` project, we're going to skip its updates all together (for now).
> Excluding `OCPSTRAT-` project from FixVersion updates

- pkg/jira/jira.go
- pkg/jira/jira_test.go
If the PR already has the comment, `return nil, true`. Returning `false` will log an error.
> bugfix on PR commenting

- pkg/jira/jira.go
- pkg/jira/jira_test.go
Remove GitHub errors from the Jira comment. Include only the generic `Internal Error on Automation`, as with the other internal errors, and only log the actual error.
> remove github errors from Jira comments

- cmd/release-controller/controller.go
- cmd/release-controller/main.go
- cmd/release-controller/sync_release.go
This PR adds a `--manifest-list-mode` flag to the commandline that enables executing `oc` commands with the `--keep-manifest-list` options specified.
> Adding Manifest List based release support

- pkg/release-controller/prowjob.go
There are a ton of logs that look like now:
`W1025 18:13:26.237275       1 prowjob.go:52] Unknown prowjob result URL prefix:`
Why?  My best guess is that prowjobs are being created and then getting triggered, which causes an update that triggers the release-controller.  I'm guessing that update is probably too early for the URL to have been populated and therefore we get this message...
These messages are useless, so this PR adds a check for an empty URL.
> Quiet noisy warning about empty prowjob URLs

- cmd/release-controller-api/controller.go
- [CNF-10171](https://issues.redhat.com//browse/CNF-10171) will be moving the internal kpi results host to be using port 80 instead of 8080
- This will align the link on the page to the new port
- The server will be temporarily listening on both ports for an interim time until all alignment work (this pr and some others in other components) are completed, at which point the server will stop listening on 8080
> CNF-10171: Update port for kpi results host

- .gitignore
- cmd/release-reimport-controller/main.go
- images/release-reimport-controller/Dockerfile
- pkg/cmd/release-reimport-controller/cmd.go
- pkg/cmd/release-reimport-controller/controller.go
This PR creates the `release-reimport-controller` which checks whether images from a release need to be reimported every 10 minutes. It takes a list of namespaces as an input and uses the `MultiImageStreamLister` to keep track of imagestreams, which should be more efficient as it receives events on changes, preventing the `release-reimport-controller` from needing to get every imagestream every 10 minutes.
> cmd: create release-reimport-controller

- pkg/cmd/release-reimport-controller/controller.go
Klog-v2 and the original klog appear to be incompatible, causing klog-v1 logs with verbosity set to not be logged.
> reimport-controller: use klog/v2

- pkg/cmd/release-reimport-controller/cmd.go
- pkg/cmd/release-reimport-controller/controller.go
This PR improves logging in the release-reimport-controller and disables the controller leader election.
> release-reimport-controller: improve logging

- cmd/release-controller-api/controller.go
- cmd/release-controller-api/http.go
- cmd/release-controller-api/http_helper.go
- cmd/release-controller-api/static/releaseDashboardPage.tmpl
- cmd/release-controller-api/static/releasePageHtml.tmpl
Follows https://github.com/openshift/release-controller/pull/575
Currently, we display the `i` icon next to all nightlies if the latest one has inconsistency. With this update, it will not display that icon.
> [OCPCRT-169] Do not show i icon if no inconsistency exist

- cmd/release-controller-api/http.go
- cmd/release-controller-api/static/imageStreamInconsistency.tmpl
Follows https://github.com/openshift/release-controller/pull/577
Changes in this PR:
- Do not display payload inconsistency if it doesn't exist
- If a user directly goes to the inconsistency page, load the streams from cluster if the variable is empty
> [OCPCRT-169] Clean up inconsistency page

- cmd/release-controller-api/http.go
- cmd/release-controller-api/static/featureRelease.html
- cmd/release-controller-api/static/htmlPageStart.html
I don't know whether it's my ISP blocking the CDN, but I receive a ERR_CONNECTION_REFUSED when accessing the jsdelivr NPM for that bootstrap version. I found an alternative mirror of it on cloudflares CDN. 
Release Page looks very pretty without CSS :)
> use cloudflare for bootstrap hosting

- pkg/rhcos/rhcos.go
Looks like a copy-n-paste error from when I first introduced this code.  This issue presents when any 2 versions of OKD-SCOS share the same version of CoreOS.  The replacement was incorrectly using RHCOS instead of CoreOS.
> Fixing incorrect string replacement

- Makefile
We're getting GLIBC errors for the reimport controller as the `cli` image is currently based on RHEL8 while the golang builder is on RHEL9. Disabling CGO will fix this mismatch.
> Makefile: disable CGO

- pkg/cmd/release-reimport-controller/controller.go
This PR adds the namespace flag and `is/` prefix to the imagestream name for the `oc import-image` command.
> reimport-controller: adjust oc import-image flags

- cmd/release-controller/sync.go
- cmd/release-controller/sync_tags.go
Currently, the release-controller's UI relies, solely, on the results stored in the respective release's ReleasePayload object and not on the verification results annotation of the ImageStreamTag.  Therefore, when a release reaches a terminal state of `Accepted` or `Rejected`, the necessity for carrying the verification results has little value any more.  This PR will cause the `release.openshift.io/verify` annotation to be deleted if/when the corresponding release reaches the `Accepted` or `Rejected` state.
As a result of this PR, and a manual cleanup effort (to purge the annotation from all Accepted/Rejected releases), it will be highly unlikely that we accumulate enough data that the size of the underlying imagestream ever reaches the maximum size of an etcd object (~1.5mb) again.
> Drop verification results annotation

- pkg/release-controller/prowjob_test.go
- pkg/release-controller/types.go
Now that the Prow results have officially been relocated to the `test-platform-results` bucket, we need to update our logic to truncate results based on the new URL.
> Updating the Prows GCS Bucket location

- cmd/release-controller-api/http.go
- cmd/release-controller/sync_verify.go
- pkg/release-controller/release.go
This will allow users the ability to filter the results down the only the versions that match the specified prefix:
`https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestream/4-stable/latest?prefix=4.14`
> Adding support for a version prefix to the latest API

- cmd/release-controller-api/http.go
- cmd/release-controller-api/http_helper.go
- cmd/release-controller-api/static/htmlPageEndScripts.tmpl
- cmd/release-controller-api/static/releaseStreamPageHtml.tmpl
This PR adds support for collapsable rows for all imagestreams on the homepage of the `release-controller-api` and adds new pages for each individual imagestream at `/releasestream/releaseConfigName` for users who wish to see the upgrade graph. Due to the massive size of the `4-stable` upgrade graph, the upgrade graph is omitted for `/releasestream/4-stable`.
> http: add collapse support for all imagestreams

- cmd/release-controller/sync_verify_prow.go
- cmd/release-controller/sync_verify_prow_test.go
There have been reports of the "aggregator" job being randomly deleted in the middle of release verification.  Unfortunately, the original implementation didn't allow for the job to be retried.  This PR adds the necessary logic to allow for the aggregator job to be retried.  To enable the logic, you can update an aggregated job as follows:
```json
"aggregated-hypershift-ovn-conformance-4.16": {
"maxRetries": 3,
"prowJob": {
"name": "periodic-ci-openshift-hypershift-release-4.16-periodics-e2e-aws-ovn-conformance"
},
"aggregatedProwJob": {
"analysisJobCount": 10
}
},
```
> Adding retry support to the Aggregator job

- pkg/release-controller/release_info.go
When generating the Changelog between releases, we make a call down into the `git-cache` pod like:
```bash
$ oc adm release info --changelog=/tmp/git/ quay.io/openshift-release-dev/ocp-release@sha256:a346fc0c84644e64c726013a98bef0f75e58f246fce1faa83fb6bbbc6d4050aa quay.io/openshift-release-dev/ocp-release@sha256:073a4e46289be25e2a05f5264c8f1d697410db66b960c9ceeddebd1c61e58717
```
When `oc` encounters an error while running the command, it:
1. Returns an error code `1`
2. Outputs the error into `stdErr`
3. Prints the truncated ouput to `stdOut`
This fix specifically checks `stdErr` for the string: ` Could not load commits for`
If it finds the string, it will log a `Warning` message with the details, swallow the error, and display the truncated output.
> Allow changelogs with missing commits

- pkg/release-controller/release.go
When verifying `Stable` releases, the release-controller reaches down into the respective release's "nightly" release configuration and runs its `Blocking` jobs as `Informing` jobs.  Due to how the `MultiJobAnalysis` jobs are performed, they are guaranteed to always fail whenever the get run against a `Stable` releases.  
This PR excludes all the `MultiJobAnalysis` from being added to the `Stable` release verification all together.
> Exclude `MultiJobAnalysis` jobs from stable release verification jobs

- hack/release-tool.py
- hack/requirements.txt
This PR supersedes #603 in that it bumps the dependency up to the `2.*` version of the `openshift-client-python` library.  Unfortunately, this will be a breaking change for anyone who attempts to run the `release-tool.py` against the older version of the library as the package name has changed from `openshift` to `openshift_client`.  This was a necessary change on the `openshift-client-python` side because there were 2 RedHat libraries attempting to use the `openshift` namespace and therefore they couldn't co-exist (https://github.com/openshift/openshift-client-python/issues/75)
> Updating to the latest/greatest `openshift-client-python`

- cmd/release-controller/periodic.go
- cmd/release-controller/sync_verify_prow.go
This PR is part of the effort of introducing a scheduler in Prow: https://github.com/kubernetes/test-infra/issues/32039.
It is a follow up of:
- https://github.com/kubernetes/test-infra/pull/32173
- https://github.com/kubernetes/test-infra/pull/32361
- https://github.com/openshift/ci-tools/pull/4044
TL;DR: we have introduced a simple scheduler in Prow, disabled by default. Once enabled via:
```yaml
scheduler:
enabled: true
```
every agent capable of creating a ProwJob should honor the configuration, hence spawing in `.status.state = scheduling`. Those are going to be picked up by the scheduler, that will assign a cluster to them and make the transition from `.status.state = scheduling` to `.status.state = trigged`. From this moment on the workflow is the same as it used to. We hope the …
> release-controller: opt-in ProwJob scheduling

- pkg/release-controller/release_info.go
All external links that have the word "demo" will be included in the Feature-Based change log.
> change the inclusion logic for demo links

- cmd/release-controller/main.go
- images/release-controller-api/Dockerfile
- images/release-controller/Dockerfile
- pkg/release-controller/release_info.go
With https://github.com/openshift/oc/pull/1708, `oc` now requires much less disk space and can be run locally without depending on an external git-cache pod. This improves availability and speed of changelog generation.
> release_info: use local `oc`

- cmd/release-controller/sync_tags.go
e.x
```yaml
- name: 4.11.0-multi
annotations:
release.openshift.io/creationTimestamp: '2022-08-09T00:01:01Z'
release.openshift.io/hash: 4.11.0-multi-102
release.openshift.io/name: 4-stable-multi
release.openshift.io/phase: Accepted
release.openshift.io/rewrite: 'false'
release.openshift.io/source: ocp-multi/release-multi
from:
kind: DockerImage
name: 'quay.io/openshift-release-dev/ocp-release:4.11.0-multi'
generation: 102
importPolicy:
importMode: Legacy
referencePolicy:
type: Source
```
The `quay.io/openshift-release-dev/ocp-release:4.11.0-multi` image holds a manifest list. After `4.13`, Openshift imagestreams are eligible to preserve the manifest list by using the `PreserveOriginal` import mode.
/cc @bear-redhat  
Signed-off-by: Nikolaos Moraitis <nmoraiti@redhat.com>
> ensure the PreserveOriginal import mode policy image tag synchronization

- cmd/release-controller/sync.go
After the changes, introduced with: https://github.com/openshift/release-controller/pull/617, went live, we started performing "rewrite" jobs for any manifest-list based releases because the label we key off of (`io.openshift.release` is never present inside of the manifest-list of "adopted" releases (i.e. .Z releases published directly into a Stable stream).  This PR checks for multiple manifests and looks for the `amd64` release to then process the label accordingly.
> Process multi-arch releases

- cmd/release-controller-api/http.go
- cmd/release-controller-api/static/htmlPageEndScripts.tmpl
- cmd/release-controller-api/static/releasePageHtml.tmpl
This adds a new column to the release streams called "Team Approvals" which list all teams that have accepted or rejected a release payload via a label with a key in the format of "...teamName_state" which can have a value of "Accepted" or "Rejected". This also prints the list of the tag's page above the test results.
> release-controller-api: print team acceptance status

- pkg/apis/release/v1alpha1/types.go
- pkg/cmd/release-payload-controller/job_state_controller.go
- pkg/cmd/release-payload-controller/job_state_controller_test.go
- pkg/cmd/release-payload-controller/prowjob_controller.go
- pkg/release-controller/prowjob.go
Prow recently introduced the `Scheduling` state for Prowjobs.  The release-controller controller does not handle this state very well and emits the following log messages every time it encounters it:
```
E0819 21:05:12.870109       1 prowjob.go:38] Unrecognized prow job state "scheduling" on job 4.15.0-0.ci-2024-08-19-205542-gcp-sdn
I0819 21:05:12.870178       1 controller.go:606] Error syncing {ocp 4.15}: unexpected error accessing prow job definition
I0819 21:05:12.870295       1 event.go:377] Event(v1.ObjectReference{Kind:"ImageStream", Namespace:"ocp", Name:"4.15", UID:"329ee0e8-7670-4fdd-9f29-6e4248c3e2f8", APIVersion:"image.openshift.io/v1", ResourceVersion:"4393617790", FieldPath:""}): type: 'Warning' reason: 'UnableToVerifyRelease' unexpected error accessing prow job definition …
```
> Adding support for prowjobs in a `Scheduling` state

- cmd/release-controller/sync_release.go
- pkg/release-controller/types.go
Introducing the `AlternateImageRepository` key to the Release Configuration to allow for release admins to specify an external location to publish `Accepted` releases into.
> Adding the `AlternateImageRepository` definition

- cmd/release-controller-api/http.go
- hack/release-tool.py
- pkg/release-controller/types.go
This PR adds the ability to `lock` and `unlock` nightly imagestreams to the `release-tool`.
To Lock:
```bash
$ ./hack/release-tool.py --execute lock 4.18
```
To Unlock:
```bash
$ ./hack/release-tool.py --execute unlock 4.18
```
> Enabling the ability to Lock and Unlock imagestreams

- cmd/release-controller-api/http_upgrade_graph.go
Adding support for `stable-scos`, `next`, and `next-scos`
> Adding support for the `stable-scos-4` upgrade channel

- cmd/release-controller/sync_publish.go
It has come to our attention that when the release-controller publishes its versioned tags, like: https://github.com/openshift/release/blob/1ee59359367cb870fcf8e55ef5a4f186b905ce53/core-services/release-controller/_releases/release-ocp-4.18.json#L18-L25
it does not specify `ImportModePreserveOriginal` as the import mode.  This PR corrects that.
> Use `ImportModePreserveOriginal` when publishing versioned tags

- cmd/release-controller/sync_mirror.go
The original logic here only overwrote the settings that it needed to for the mirrored tags.  So, instead of overwriting the whole `ImportPolicy` all together, I'm going to revert back to the original style and just overwrite the `ImportMode` as well.
> Adjust logic to overwrite `ImportPolicy.ImportMode`

- pkg/rhcos/rhcos.go
The RHCOS release browser has been moved from the ocp virt cluster to the ITUP.stable cluster.
See: https://issues.redhat.com/browse/COS-2767
> Update the RHCOS Release Browser URL

- pkg/rhcos/rhcos.go
Update the version map to include `9.6` to fix the broken link between the ocp release browser and the rhcos release browser when viewing `4.19` builds.
> Add 9.6 version map to fix RHCOS browser link

- cmd/release-controller-api/http_changelog.go
- pkg/release-controller/release_info.go
- pkg/rhcos/rhcos.go
As part of https://github.com/openshift/enhancements/pull/1637, the CoreOS pipeline now only builds a RHEL-only RHCOS base image and later on, a node image is built on top of this base image to add all the OCP-specific packages.
As a result, the RHCOS release browser will only display the diff of the _base_ image content, and will not have any OCP content.
Often, that's sufficient. E.g. if you're just interested in kernel or systemd changes, the RHCOS release browser is enough. However, users can be confused by the lack of OCP packages in the list.
Let's add an info box to the changelog page with instructions to generate a full diff. But only display it if one of the RHCOS versions is of the new RHEL-only kind.
As a bonus, these instructions also conveniently serve as a way to get any …
> rhcos: add info box with RPM diff command if necessary

- hack/release-tool.py
While working on an update, I noticed that the messaging when deleting an approval was incorrect.  This PR fixes the message.
> Correct messaging when deleting team approval

- hack/release-tool.py
It's hard to reliably retrieve ReleasePayloads based on labels with inconsistent formatting.  This PR forces the team approval labels to always be persisted with lowercase team names.  The UI utilizes `ToUpper()`, so this shouldn't cause any issues with existing logic.
I have manually went and corrected the handful of ReleasePayloads that had UPPERCASE team names already.
> Always label ReleasePayloads with the lowercase team name

- cmd/release-controller-api/http.go
- cmd/release-controller-api/http_helper.go
- pkg/release-controller/release_payload.go
- pkg/release-controller/types.go
Adding an API that provides a way to get releases that have been marked as `Approved` by teams.  This PR introduces the `/api/v1/releasestreams/approvals` to the `release-controller-api`.  The API behaves as follows:
When called directly, like:
`https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestreams/approvals`
The API will return a JSON array of all releases that have been flagged as `Approved`, in descending order (from the most recent to the oldest release versions (by SemVer comparison)
These results can be filtered down by specifying any combination of the following query parameters:
- `team` - releases that have been `Approved` by the specified team
Examples:
`https://amd64.ocp.releases.ci.openshift.org/api/v1/releasestreams/approvals?team=trt` …
> Introduce an approvals API

- cmd/release-controller/sync_release.go
- pkg/release-controller/types.go
In an effort to work around an issue generating releases from konflux, we're introducing the `disableManifestListMode` override to allow for individual release streams to turn off creating manifest list based releases while the details of: https://issues.redhat.com/browse/OCPBUGS-50660 are being sorted out.
> Introducing the `disableManifestListMode` flag to the `ReleaseConfig`

- cmd/release-controller-api/http.go
- go.mod
- go.sum
- pkg/release-controller/release_info.go
- vendor/github.com/patrickmn/go-cache/CONTRIBUTORS
- vendor/github.com/patrickmn/go-cache/LICENSE
- vendor/github.com/patrickmn/go-cache/README.md
- vendor/github.com/patrickmn/go-cache/cache.go
- vendor/github.com/patrickmn/go-cache/sharded.go
- vendor/modules.txt
Re-enable the Feature Analysis again. 
Pending a larger refactoring, improve in-memory caching of Jira issues, to limit the API calls as much as possible. 
Limit the API calls to a maximum of 1 call per second.
> Refactor feature analysis

- cmd/release-controller/sync_verify_prow.go
This environment variable is being added, to all release-controller jobs, to override the default value of "true", specified in the Step definition.  Why? The variable is being added as a cost saving mechanism that forces everyone to utilize Public worker nodes and bypassing any NAT Gateway expenses on their clusters.  The release-controller must run its verification tests against "real" clusters and therefore, we're overriding this value.
> Specifying `OPENSHIFT_INSTALL_AWS_PUBLIC_ONLY=false` for all verification jobs

- cmd/release-controller-api/http.go
If the feature analysis takes longer than 15 seconds to load, return a wait-and-come-back-later message.
> improve  feature analysis loading

- cmd/release-controller/sync.go
- cmd/release-controller/sync_release.go
The current logic creates a job named like: `4.19.0-0.ci-2025-04-02-113804-alternate-mirror`, but also uses that same name for both the `fromImage` and `toImage`, which does not exist.  This PR updates the logic to only set the "alternate-mirror" name for the Job itself.
> Fixing release mirror job naming problem

- cmd/release-controller/sync_release.go
Use the correct name for the job base for release mirror jobs.
> sync_release: fix mirror job name

- cmd/release-controller/sync_release.go
The `ensureReleaseMirrorJob()` method relies on `release.Config.AlternateImageRepository` being set.  This PR performs a check to ensure that there is a value before creating a job that will never succeed:
```
Command:
/bin/bash
-c
set -eu
mkdir -p "${XDG_RUNTIME_DIR}"
oc registry login
oc image mirror --keep-manifest-list=$1 $2 $3
true
registry.ci.openshift.org/ocp/release:4.20.0-0.ci-2025-04-02-143700
:4.20.0-0.ci-2025-04-02-143700
State:      Terminated
Reason:   Error
Message:  info: Using registry public hostname registry.ci.openshift.org
Saved credentials for registry.ci.openshift.org into /tmp/run/containers/auth.json
error: ":4.20.0-0.ci-2025-04-02-143700" is not a valid image reference: invalid reference format
Exit Code:    1
```
> Adding a nil check for AlternateImageRepository

- cmd/release-controller-api/http.go
- cmd/release-controller-api/http_changelog.go
- pkg/release-controller/release_info.go
- pkg/rhcos/rhcos.go
This basically fixes the gap that the infobox added in #648 warns about. Instead of relying on the CoreOS release browser differ, we directly query for the diff using `oc adm release info`, which recently learned to do this, and render it at the bottom of the page.
This removes the VPN requirement on being able to see the RPM diff.
In the case of the new layered node images, replace the diff link to instead link to this new rendered section. We could in theory always link to that, but let's be conservative. This provide a natural rollout of the feature in case it needs ironing out.
Implementation-wise, we don't want to block the main changelog render on getting the RPM diff. So we structure this the same way as the changelog render itself; if the `oc` command takes too long, we display a …
> release-controller-api: render RPM diff

- pkg/cmd/release-payload-controller/job_state_controller_test.go
- pkg/cmd/release-payload-controller/legacy_job_status_controller_test.go
- pkg/cmd/release-payload-controller/payload_accepted_controller_test.go
- pkg/cmd/release-payload-controller/payload_creation_controller_test.go
- pkg/cmd/release-payload-controller/payload_rejected_controller_test.go
- pkg/cmd/release-payload-controller/payload_verification_controller_test.go
- pkg/cmd/release-payload-controller/prowjob_controller_test.go
- pkg/cmd/release-payload-controller/release_creation_job_controller_test.go
- pkg/cmd/release-payload-controller/release_creation_status_controller_test.go
This PR updates all Release Payload Controller unit tests to use `New...Controller` functions instead of manually creating the structs. It also adds `t.Parallel` to all tests. This reduces test runtime for the `pkg/cmd/release-payload-controller` package from 7 seconds to 1.4 seconds on my system.
> release-payload-controller/*test.go: improve tests

- cmd/release-controller/controller.go
Taking a little more aggressive action against the release-controller's Jira limits.  This PR will reduce the number of Jira Workers from 3 down to 1.  This will absolutely slow down our jira validation process, but hopefully it's only temporary until we get out of Jira jail.
> Drop to a single Jira Worker

- pkg/releasepayload/jobrunresult/helpers.go
- pkg/releasepayload/utils.go
It was reported that the release-controller was not displaying the latest/greatest results for a verification job.  After investigating, it turns out that there is a bug in the display logic...
Basically, the `release-payload-controller` sorts all the `JobRunResults`, for a given validation job, by their respective `Coordinate.Name` value (for generating a canonical version of the resource).  Unfortunately, in some occasions, this results in the list not being in the order that the `release-controller-api` was expecting.
This PR adds logic to sort all `JobRunResults`, of a given job, by its `StartTime`, and then chooses the "latest" results to display.
> Always display the latest prowjob result

- pkg/cmd/release-mirror-cleanup-controller/cmd.go
- pkg/cmd/release-mirror-cleanup-controller/controller.go
Use credentials to operate on alternate repo registries.
> release-mirror-cleanup-controller: use registry secrets

- pkg/cmd/release-mirror-cleanup-controller/cmd.go
Make cleanup interval configurable via a flag and change default interval to 24 hours.
> mirror-cleanup-controller: add interval flag

- cmd/release-controller-api/controller.go
- This results page has been deprecated and replaced with a new reporting portal
- See details in https://issues.redhat.com/browse/TELCOV10N-445
> TELCOV10N-447: Remove link to Telco CI results

- pkg/cmd/release-payload-controller/prowjob_controller.go
- pkg/cmd/release-payload-controller/prowjob_controller_test.go
- pkg/releasepayload/utils/release-verification-job-details.go
- pkg/releasepayload/utils/release-verification-job-details_test.go
When the OKD folks introduced the `okd-scos` naming, they inadvertently broke the `releasepayload` processing logic for the majority of the "Stable" streams:
https://amd64.origin.releases.ci.openshift.org/#4-scos-next
https://amd64.origin.releases.ci.openshift.org/#4-scos-stable
The corresponding Prowjobs, for these releases, were being launched by the `release-controller`, but were not being picked up and processed by the release-payload controller.  
The issue was caused by the processing, of the prowjob names, not being able to correctly determine the `ciConfigurationName` name for these jobs.  This resulted in the jobs always showing up as "greyed out" on their respective release status page, like:
This PR completely overhauls the prowjob name processing logic and adds OKD specific …
> Adding support for OKD releases with okd-scos naming
